### ISSUE TITLE
Trim whitespace from input fields by default

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2024]
Feature proposal: To trim by default leading trailing whitespace from entry input fields.

I can not think about a use case where I would need a whitespace around (on the data level), or solely a whitespace as an input value. Under contrary, such a whitespace is mostly unwanted.

I mentioned it firstly in the [forum](http://www.getsymphony.com/discuss/thread/105924/) to discuss it at first. @designermonkey pointed me to Mark's [extension](http://symphonyextensions.com/extensions/lazy_input_correction/), but actually this trim feat could be a part of the core functionality.

How do you see it?

PS: Also maybe, if added, Symphony update process could walk all the fields and clean up existing fields accordingly.

**Comment by michael-e** [comment]
@brendo: I think we forgot to bring this change to Symphony 2.6. What a shame.

**Comment by jensscherbl** [comment]
@michael-e I think it's considered a breaking change and therefore planned for `3.0.0`.

**Comment by michael-e** [comment]
@jensscherbl: Thanks.

One more thing: I am not sure if we have an open issue for (or already solved) another phenomenon that may bring down pages of your website with XSLT errors: In Symphony 2.3, from time to time people manage to post line breaks in Input fields (which obviously is possible in Internet Exploder if you copy/paste the line break to the field). Symphony then throws an XSLT error, because the handle for the field will have a line break.

Does anybody know if we already discussed or solved this?

**Comment by michael-e** [comment]
Since the client managed to again break a page by copy/pasting, I did some investigation. The client had a Powerpoint document that contained a "vertical (!) Tabulation" character (VT, Unicode 0x0B). Using this character in a Symphony input field definitely creates a handle that will break your page output (containing the said control character). If you manage to get this handle into a decent text editor, it will look like:

![bildschirmfoto 2015-03-09 um 17 39 26](https://cloud.githubusercontent.com/assets/40072/6559436/59bd14cc-c683-11e4-93ce-12f0cf5b60d8.png)

I am so fed up. I don't want these characters at all—neither in the handle nor in the field's value. So I didn't think about adding anything to the transliteration array. Instead, now I hacked my Symphony installation to remove all control characters and trim the input string. For me this looks like the way to go, really. In the `FieldInput` class, I added the following to the `processRawFieldData()` function:

```php
$data = trim(preg_replace( '/[\x00-\x1F\x7F]/', '', $data));
```

@brendo: Should I open another issue for the control character problem? Or shall we solve it altogether using this "hack" (or something similar)?

**Comment by nitriques** [comment]
@michael-e I've, too, been tired of this for a long time now. I had a client who was copy-pasting from pdf and had all kind of funky chars in it. Please guys, let's fix this :) Thanks.

**Comment by michael-e** [comment]
We probably can't solve all kind of funky characters that can be found in PDFs. But at least control characters should be stripped.

We can also think about the Textarea Field. Here I would suggest to strip out all control characters except whitespace characters.

**Comment by nitriques** [comment]
> We probably can't solve all kind of funky characters that can be found in PDFs. But at least control characters should be stripped.

Exactly.

**Comment by jensscherbl** [comment]
Already on the todo-list for `3.0.0`. See #2106

**Comment by brendo** [comment]
> @brendo: Should I open another issue for the control character problem? Or shall we solve it altogether using this "hack" (or something similar)?

New issue. I can't say any scenarios where someone would want the control character. This could be fixed in a 2.6.1.

> Already on the todo-list for 3.0.0. See #2106

That's slightly different, but will help too.

**Comment by michael-e** [comment]
OK, I will open another issue for control characters. However, as often, things are not as simple as they seem. We will have to make some decisions…

**Comment by brendo** [comment]
Done. In Symphony 3.0.0, whitespace is trimmed from the Input field by default.
