### ISSUE TITLE
Datepicker UI

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2295]
Not sure about it, but what do you think about restricting the width of the datepicker? Looks a bit stretched at the moment.

![screen shot 2014-12-14 at 17 05 32](https://cloud.githubusercontent.com/assets/1640033/5435366/10d998cc-845a-11e4-8f5d-d908546bca14.png)

I would also prefer a floating datepicker (like in the filtering ui above) for the entry instead of the inlined one (below).

![screen shot 2014-12-14 at 17 06 21](https://cloud.githubusercontent.com/assets/1640033/5435423/acfff44e-845a-11e4-8857-11d0f13cccb5.png)

I still think of this as a temporary thing until browsers finally implement the native HTML5 datepicker, and that we just get rid of it and switch from `input type="text"` to `input type="date"` in the future.

**Comment by nitriques** [comment]
> A max-width makes sense to me. feels unusable too wide in main column

I agree !

**Comment by animaux** [comment]
I agree with folks wishing for a collapsible floating date-picker or at least have the option to decide between floating and always-open.

**Comment by brendo** [comment]
This might be a silly question, but if it looks silly in the main column, why not just switch it to the secondary column? Isn't this the same issue as putting SSM in the main column, or a checkbox field?

Isn't the UI going to look more strange if you have a series of inputs in the main column of differing widths?

> I agree with folks wishing for a collapsible floating date-picker or at least have the option to decide between floating and always-open.

I just want to highlight something here. This is the reason why these interface elements are often left out of the core. There is so many permutations of what each developer would like the interface to do that it starts to overly complicated the settings of a field. Suddenly the date field has settings for time on/off, calendar on/off, floating calendar on/off, week offset 0-6 etc. Previously there was one setting, pre-populate with the current time. It provided a base that extensions could extend from. When we start to go down the road of implementing an interface, suddenly it becomes far more involved as everybody has differing use cases.

This isn't to pick on anyone, it's just highlighting the reason why the core generally prefers not to build these UI elements (filtering is another example). Extensions can often do it better, and give developers more choice. I prefer this instead of having 'mega' extensions that come with a heap of settings and different permutations.

**Comment by jensscherbl** [comment]
> This might be a silly question, but if it looks silly in the main column, why not just switch it to the secondary column?

I usually don't use the secondary column. I also have a custom extension that gives publish forms a little bit more structure.

![Uploading Screen Shot 2014-12-15 at 14.02.49.png . . .]()

> Isn't this the same issue as putting SSM in the main column, or a checkbox field?

I don't use SSM. Checkbox fields are fine.

> Isn't the UI going to look more strange if you have a series of inputs in the main column of differing widths?

Yep, that's why I'd prefer a normal input field with a floating datepicker ui.

**Comment by nilshoerrmann** [comment]
> Finally, if the core implements a UI, it's often harder for an extension to override that UI with it's own. This creates a scenario where the developers ask the core to include option 'x' and 'y' because it's simpler easier to get the core to do it instead of the extension. This loops goes on for awhile until we get tired of managing so many settings/variations that we just cut it from the core and push it back out to extension developers :package: 

May I suggest to bundle the Calendar with the core but only use it for the filtering interface? It's especially useful for the later because it makes sure the correct date format (American) is used for filtering.

The UI for the date field can be enabled by an extension (using either the floating variant or the fixed one or even introducing an additional one that's expanding/collapsing on click). The calendar is set up in a way that more complex fields like Date and Time can use it as well.

**Comment by animaux** [comment]
@nilshoerrmann very good suggestion!

**Comment by nathanhornby** [comment]
Id personally like to see the field have some kind of basic calendar UI, it's always felt messing one - otherwise we might as well also swap out the checkbox field for an input that accepts 'yes' or 'no'. Let the UI be handled by an extension. Why even bundle CSS with Symphony? ;)

There's a point where pushing things out to extensions gets downright excessive!

**Comment by nathanhornby** [comment]
Also

> Id personally like to see the field have some kind of basic calendar UI

If for no other reason than we know it'll be maintained.

**Comment by animaux** [comment]
@nathan good points too. I’m obviously too easily convinced and will likely adopt the next opinion mentioned here :)

**Comment by nathanhornby** [comment]
Haha that's normally my role!

**Comment by nilshoerrmann** [comment]
Just keep in mind that removing the calendar from the date field for 2.6 doesn't mean the core cannot use it in a later version. Symphony now uses semantic versioning so we'll have a much quicker release circle.

This discussion reminds me a bit of the 	phrase: "Give him an inch and he will take a mile." :)
The introduction of the calendar was kind of a farewell present before leaving the core team (it was the last thing on my Symphony todo list) but it's just the first step. There are talented interface designers in the community, so it will be maintained and improved.

From a core perspective:

- The date field traditionally bundled a fixed calendar (Symphony 1). We are reviving that concept.
- The date field defaults to the sidebar, which is why the interface focusses on that area first.
- The calendar is optional.

Symphony also bundles a floating variant used by the filtering interface which could be reused by the date field. There are also other interfaces possible (think of the Duplicator style used by Date and Time) and these variants/enhancements can be implemented using extensions right now.

We just should try to solve all use cases at once. 
Think of the calendar as the starting point for a unified date handling across the core and its extensions. Emphasis on _starting point_.

If the date fields calendar doesn't work for you yet: don't use it now – you don't have to. Improve it, iterate the implementation over the next Symphony versions.

**Comment by animaux** [comment]
> Symphony also bundles a floating variant used by the filtering interface which could be reused by the date field. (…) and these variants/enhancements can be implemented using extensions right now.

Could the floating behavior be trigged with some js with something like the `backend_addscript` extension?

**Comment by nilshoerrmann** [comment]
If the calendar markup is wrapped with an `.suggestion` element, the behaviour will change. Just have a look a the filtering UI.

I cannot promise that it works out of the box because the floating layout has been taylored for the filtering UI specifically. But – again – it's a starting point for the floating display in the field view.

**Comment by animaux** [comment]
Thanks Nils, will have a look.

**Comment by animaux** [comment]
@jensscherbl maybe you want to have a go at an extension to make the calendar float? :) Not sure if I’m able to make this …

**Comment by jensscherbl** [comment]
I don't like the idea of having a hundred settings for stuff like this. I also don't like the idea of having to overwrite or remove existing core behaviour in extensions, always feels a bit hacky to me.

If we can't agree on a fitting UI for everyone here, I think what @nilshoerrmann proposed above is the right way to go.

> May I suggest to bundle the Calendar with the core but only use it for the filtering interface?

The UI for the date field can be enabled by an extension (using either the floating variant or the fixed one or even introducing an additional one that's expanding/collapsing on click). The calendar is set up in a way that more complex fields like Date and Time can use it as well.

> If for no other reason than we know it'll be maintained.

I think I have a solution for this problem (will discuss in a separate issue soon).

**Comment by nitriques** [comment]
DateTime is (for me) a native UI, just like checkboxes and button. input type=date is landed, but stills lacks what CLNDR offers. I would vote for it to stay in the core.

**Comment by nilshoerrmann** [comment]
Due to timezone issue (see #2312), we now have two pending pull requests:

- #2325 that removes the calendar for Symphony 2.6 and
- #2326 that adds it again for Symphony 2.7

This issue can be handled alongside #2326.

**Comment by nitriques** [comment]
Thanks Nils.

**Comment by brendo** [comment]
I don't do this often, but I'm going to put my foot down on this one. For consistency between the filtering and the date field, the calendar will be a dropdown. To make the calendar more manageable, a max width has also been introduced. 

I believe this is a smart default and a better solution than a setting.

**Comment by animaux** [comment]
:+1: Totally with you on this one :)

**Comment by jensscherbl** [comment]
> I don't do this often, but I'm going to put my foot down on this one. For consistency between the filtering and the date field, the calendar will be a dropdown. To make the calendar more manageable, a max width has also been introduced.

I believe this is a smart default and a better solution than a setting.

+1 :)

**Comment by brendo** [comment]
Closing down.
