### ISSUE TITLE
Date Field calendar fails when backend language is set to german

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2306]
Title says it all. When the backend language is set to `german` I get JS-errors in the edit-page when a data field calendar is used:

    [Warning] Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info. (symphony.min.js, line 88)

+

    [Error] TypeError: undefined is not an object (evaluating 'daysArray[daysArray.length-1].date')
        createDaysObject (symphony.min.js, line 93)
        render (symphony.min.js, line 93)
        init (symphony.min.js, line 93)
        c (symphony.min.js, line 93)
        clndr (symphony.min.js, line 93)
        q (symphony.min.js, line 96)
        k (symphony.min.js, line 96)
        (anonyme Funktion) (symphony.min.js, line 97)
        each (symphony.min.js, line 14)
        each (symphony.min.js, line 14)
        (anonyme Funktion) (symphony.min.js, line 97)
        execute (symphony.min.js, line 32)
        dispatch (symphony.min.js, line 32)
        dispatch (symphony.min.js, line 32)
        parse (symphony.min.js, line 37)
        render (symphony.min.js, line 96)
        (anonyme Funktion) (symphony.min.js, line 97)
        k (symphony.min.js, line 24)
        fireWith (symphony.min.js, line 24)
        ready (symphony.min.js, line 24)
        g (symphony.min.js, line 14)

All is well when backend language is switched to english.

Nils suggested the root of evil might be in this line: https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L22

**Comment by nilshoerrmann** [comment]
My guess is that the language string is not correct or at least not recognised correctly.

**Comment by nilshoerrmann** [comment]
Note to @brendo: This needs to be fixed before the first RC because the issue literally affects all localised systems. I'm working on a Symphony project this week and hope to find the time to look at it along the way.

**Comment by brendo** [comment]
So looking at this at the moment (I've updated jQuery, Moment and Calendar plugins as well), it seems that it's caused by the `lang_german` extension setting the default date format to `d. F Y`. The mappings in the [`DateTimeObj` class](https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/core/class.datetimeobj.php#L41) don't include a value for this, so no format is added to the Calendar widget. This then has the knock-on effect because moment can't parse the German date and neither can the browser.

So adding a new record for the `d. F Y` fixes the issue, but I'm wondering if the actual fix should be in the `lang_german` extension? Is `02.January 2015` natural in German?

**Comment by brendo** [comment]
Apologies @nilshoerrmann, I kept running with this (JS and CSS instead of PHP for change)! What I've done is just make the calendar abort if there is no `format` available. I think this is a better experience instead of having a broken calendar display. Still up for your input on the german date format though :)

**Comment by nilshoerrmann** [comment]
> Is 02.January 2015 natural in German?

Yes, it is (without the leading `0` though). These are the most common German formats:

- 2. Januar 2015 (text)
- 2.1.2015 (text)
- 02.01.2015 (tabular data)

So the German language extension should use `j. F Y` instead of `d. F Y` if I'm not mistaken.

> So adding a new record for the d. F Y fixes the issue, but I'm wondering if the actual fix should be in the lang_german extension?

We could remove this setting form the language extension but users are allowed to set the system date to any valid PHP data string. So this doesn't fix the issue.

What about this:

- We disable the calendar, if the format is not recognized.
- We give extensions a way to extend `$date_mappings` so missing dates can be added by language extensions, if needed.

**Comment by nilshoerrmann** [comment]
Ah, you moved along already – so we agree on disabling the calendar. What do you think about extending the mappings?

**Comment by brendo** [comment]
> Ah, you moved along already – so we agree on disabling the calendar. What do you think about extending the mappings?

Yep sorry. Yeah, I think for maximum compatibility extensions should be able to change those mappings. Not exactly too sure how this would happen at the moment, we don't know where a translation comes from at the minute.

**Comment by nilshoerrmann** [comment]
Well, the calendar is new in 2.6 so we _can_ introduce it with some restrictions. One might be the dependance on predefined date formats. The current mapping should contain the most common formats – we've updated the list a while back with missing European formats. The problem with the German translation _is_ – as you discovered – a wrong format definition that can be solved within the extension easily.

What about adding a note in the console in cases the system doesn't recognise the format? Maybe even suggesting working alternatives (just referencing the class with the mappings might be confusing because of the mixture of PHP and Moment definitions). That message should automatically be written to the system log as well, if I'm not mistaken.

So in the case of an incompatible format, the calendar in the publish filtering interface will work non the less, because it relies on a standard American date format. Only the calendar of the date field will be affected.

**Comment by nilshoerrmann** [comment]
There is now a dedicated function to disable the field calendar. It adds the following note to the browser console:

```
The Symphony calendar widget has been disabled because your system date format is currently not supported. Try one of the following instead:

 - Y/m/d (2015/01/08)
 - d/m/Y (08/01/2015)
 - m/d/Y (01/08/2015)
 - m/d/y (01/08/15)
 - Y-m-d (2015-01-08)
 - m-d-Y (01-08-2015)
 - m-d-y (01-08-15)
 - d.m.Y (08.01.2015)
 - j.n.Y (8.1.2015 – no leading zero)
 - j.n.y (8.1.15 – no leading zero)
 - d.m.y (08.01.2015)
 - d F Y (08 January 2015)
 - d M Y (08 Jan 2015)
 - j. F Y (8. January 2015)
 - j. M. Y (8. Jan. 2015)
```

That message is only shown if the calendar is actually used _and_ the date format is unknown. The suggestion list is generated dynamically and will feature all formats available in the system. The preview always shows today's date.

**Comment by nitriques** [comment]
+1
