### ISSUE TITLE
Date Field calendar: week starts with sunday

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2312]
In germany it’s uncommon to have the week starting on sunday. Is there a way to select monday as well? Can this be reflected by the language settings somehow?

**Comment by nilshoerrmann** [comment]
Sunday is the default start of the week in JS (don't ask!). CLNDR offers an offset setting, so yes this can be customised.

**Comment by animaux** [comment]
Should we have this as an option of the date field then, or rather have a language extension trigger the right behaviour (if possible)?

**Comment by nilshoerrmann** [comment]
If we allow an offset, it should be a system preference in my eyes because the calendar is used for date fields and publish filtering – relying on localisations is restrictive because you cannot just set your week start to Wednesday and might also be confusing conceptually. I didn't want to introduce such feature until we know the calendar itself is stable.

**Comment by animaux** [comment]
I agree. Still, a week starting on sunday is quite a usability problem in german.

**Comment by nilshoerrmann** [comment]
Calling @nitriques and @brendo for some thoughts on this.

**Comment by nitriques** [comment]
We have the same problem here: Canada uses Sunday while US use Monday.

I have a couple of ideas on how to solve this:

1. A new setting in config.php
2. Using the php's locale to automatically get it
3. Use the author's locale to try and guess it

But I would vote for number one. @brendo ?

**Comment by nilshoerrmann** [comment]
Only number 1 is predictable across users. So I'd vote for that.

**Comment by animaux** [comment]
I’ll have number 1 too. Without onions and garlic.

**Comment by nilshoerrmann** [comment]
From the interface perspective, we'd just have to pass CLNDR a value for `weekOffset` (`0` for sunday etc.).

**Comment by nitriques** [comment]
CLNDR seems to represent 0 as Sunday (and so does php w formatter) so the setting could be a simple integer.

I would also add this setting in the installer. But would you add it to the preference page too ?

**Comment by nilshoerrmann** [comment]
> But would you add it to the preference page too ?

No, if it's the only setting.
Yes, if the date and time formats can we updated as well.

Personally, I'd prefer the latter – but for some reason this has never been editable in Symphony 2 (it was editable in version 1).

**Comment by nitriques** [comment]
> Personally, I'd prefer the latter 

Yeah I agree with you. And this change would be a nice kick in the ass to add them all on the preference page.

**Comment by nilshoerrmann** [comment]
To clarify my previous post: If a setting is added to the preference page, Symphony should only offer supported date and time formats as it does in the installer (they are the ones supported by the calendar widget). Custom format should still be handled manually in the config.

**Comment by nitriques** [comment]
Perfect. That's what I originally understood, but it never bad to clarify (and document) more.

**Comment by nilshoerrmann** [comment]
Would you mind adding the preferences, @nitriques? I could update the Calendar based on that.

**Comment by nitriques** [comment]
Yes I'll do it ASAP.

**Comment by nilshoerrmann** [comment]
I updated the calendar already so I looks for a value `weekoffset` in `Symphony.Context`.
If you [pass the setting (`0` to `6`) to the Symphony object here](https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.administrationpage.php#L368-L389), everything should work as expected.

**Comment by nitriques** [comment]
Awesome.

**Comment by brendo** [comment]
> Personally, I'd prefer the latter – but for some reason this has never been editable in Symphony 2 (it was editable in version 1).

I believe settings that shouldn't be modified frequently were removed from the interface to keep it brief and minimal. It's not every day you want to change your date formats on the site. I'm happy for this to be added to the installer UI, but I'd prefer if it was a hidden setting in the backend still.

**Comment by nitriques** [comment]
Cool! So I'll only add it into the installer for now. Will to it tomorrow (today for you!).

**Comment by nitriques** [comment]
There you go, send PR immediately! Turns out it was super easy to do :smile:

**Comment by brendo** [comment]
While I've merged @nitriques code, there is one usecase that has been omitted. This setting deals with full site localisation (System > Preferences). It doesn't deal when an Author overrides their backend language with something else.

For example, an German install that has myself as an Author. I'd override the language for my Author to be English, yet the calendar's would still start at the German offset.

The only way I can see to resolve this as well is to have an accompanying week offset on the Author page as well. I don't think having mixed installs is a huge percentage of users (could be wrong though!), but it's definitely one to consider.

**Comment by nitriques** [comment]
@brendo This is what I implied with my number 3.

```
Use the author's locale to try and guess it
```

But it would need a value per supported language which may be nasty.

**Comment by jonmifsud** [comment]
Maybe it should be packaged with the language extensions? And applied to
authors who have that language set?

**Comment by nilshoerrmann** [comment]
The same is true for date formats, @brendo. Similar to the language settings, it would be necessary to have global and author settings (prefs + authors). So I'm not sure this is true:

> It's not every day you want to change your date formats on the site.

It might just not be an common task if you are looking at a single author.

**Comment by nilshoerrmann** [comment]
> Maybe it should be packaged with the language extensions? And applied to
authors who have that language set?

The German localisation tried to achieve that and it's not working well with the core right now.

**Comment by animaux** [comment]
Hach! Watching you guys is like listening to a Symphony®!

**Comment by nilshoerrmann** [comment]
Symphonie fantastique.

**Comment by nitriques** [comment]
:dancer:

I agree with @nilshoerrmann on that: Every 'region' setting should customizable per author. I kind of setup thing weird since I use French date format with the English version...

**Comment by animaux** [comment]
The weekoffset is not yet saved after defining it in the `2.6.0beta2` install process. It can be easily added afterwards though and then works as expected. I guess this still needs to be implemented?

However, a currently worse problem is a wrong `@weekday`-number in the xml-output when using the german `'weekoffset' => '1'`. This results in the format-date utility displaying the wrong weekday.

**Comment by animaux** [comment]
ARGH! The problem is even worse but different. The @weekday XML-output is fine. BUT the weekoffset results in the calender moving the weekday to a wrong position instead of merely changing the week-display! :(

real weekdays:

![skjermbilde 2015-01-16 kl 21 20 19](https://cloud.githubusercontent.com/assets/446874/5783696/bd472e10-9dc5-11e4-85af-5df8ddeaf482.png)

`'weekoffset' => '1'`:

![skjermbilde 2015-01-16 kl 21 20 28](https://cloud.githubusercontent.com/assets/446874/5783704/cc605098-9dc5-11e4-92c6-7f6b78c3c84a.png)

**Comment by animaux** [comment]
Update: Weekdays are displayed wrongly even after removing the `'weekoffset' => '1'` again. So this seems to be another problem.

**Comment by brendo** [comment]
I would expect a `weekoffset` of `0` to result in the calendar displaying as S M D M D F S (German names). Moving to `1` would shift Sonntag to the end of the list, which looks like it is happening. @animaux, what is the expected output for you?

**Comment by animaux** [comment]
The weekoffset seems to work fine. But the 1st of January is *not* a Wednesday!

`'weekoffset' => '0'`

![0](https://cloud.githubusercontent.com/assets/446874/5789495/7f77ea4a-9e6d-11e4-9ba5-920419172db1.png)

`'weekoffset' => '1'`

![1](https://cloud.githubusercontent.com/assets/446874/5789496/867ece80-9e6d-11e4-9cbf-67398ba6edb5.png)

Actual Weekdays in January 2015:

![real](https://cloud.githubusercontent.com/assets/446874/5789497/980b728e-9e6d-11e4-9695-8202e5509cc3.png)

**Comment by nilshoerrmann** [comment]
So the calendar is not being calculated correctly, right? I didn't notice something alike before.
Which browser are you using? Is this behaviour consistent across browsers? And is your computer calendar working correctly (the calendar is generated client side)?

We should also check if the [updated build scripts](https://github.com/symphonycms/symphony-2/commit/cfffaf635ce7b9f6e311a077adc42e93851939fd) or the [updated JavaScript libraries](https://github.com/symphonycms/symphony-2/commit/be024fecf73b1e534510c18cee198b6990a50e46) interfer here somehow (CLDNR, Moment and jQuery have all been updated).

**Comment by brendo** [comment]
It's quite strange, it's as if `weekoffset` just 'changes history'. Making it `3` moves January 1st to Montag, which is even worse. Quite strange.

**Comment by animaux** [comment]
This behaviour is consistent within two different installations of `2.6.0-beta2` I am currently working at. I double-checked the iCal calender with other analog calendars as well, so this should be fine. 1st January 2015 is a thursday :)

**Comment by animaux** [comment]
@brendo same here :(

**Comment by brendo** [comment]
So if I remove [`weekOffset`](https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L136) from this line, and set it as `1` in my configuration file I get the correct result for German locale. The calendar changes to start the week on the Monday and Jan 1st is a Thursday.

**Comment by animaux** [comment]
@brendo no, wait! `'weekoffset' => '3'` is not changing the weekday-day relationship. It makes the week start on »Mittwoch«.

As I wrote before the weekoffset seems to do the right thing. It’s just that the weekdays are offset by a day.

**Comment by brendo** [comment]
Ah, so it'll be because of [this line](https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L169).

**Comment by nilshoerrmann** [comment]
No, that line only takes care of the headlines. They are generated independently.

**Comment by brendo** [comment]
Hmm, quite curious then, I'm still looking at it.

**Comment by nilshoerrmann** [comment]
Just to be sure we are looking at the same thing:

- Alex is using an `weekoffset` of `1` on a localised system (German)
- Brendan is using an `weekoffset` of `1` and `3` on a non-localised system (English)

Is that correct?

**Comment by animaux** [comment]
@niels yes.

Hmn, commenting out [Line 136](https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L136) actually doesn’t change anything here.

**Comment by nilshoerrmann** [comment]
> Hmn, commenting out Line 136 actually doesn’t change anything here.

What does "doesn't change anything" mean?

**Comment by brendo** [comment]
> Brendan is using an weekoffset of 1 and 3 on a non-localised system (English)

No, I'm actually pretending to be German :) I've changed my config to be `Europe/Berlin` and my laptop timezone to be Berlin as well. I have found that my [first comment](https://github.com/symphonycms/symphony-2/issues/2312#issuecomment-70469763) seems to produce the most reliable results.

`weekOffset` = 0 => Week starts on Sonntag
`weekOffset` = 1 => Week starts on Montag

In both scenarios the 1st of January stays as Donnerstag.

**Comment by brendo** [comment]
Which I might add backs up the CLDR documentation:

> If you are using a moment.js language configuration in which weeks begin on a Monday (e.g. French), Clndr will detect this automatically and there is no need to provide a weekOffset or a daysOfTheWeek array.

**Comment by animaux** [comment]
>> Hmn, commenting out Line 136 actually doesn’t change anything here.

> What does "doesn't change anything" mean?

In Calendar: January still starts on Wednesday instead of thursday. Week starts on Monday. (width `'weekoffset' => '1',`)

**Comment by nilshoerrmann** [comment]
The thing is, the offset has to work independendly of the used locale. I might have a German backend but still want my week start on Saturday (which – for instance – is the day the TV program usually starts with). So we might have a conflict between the automatic locale handling of CLDNR and the week offset.

> No, I'm actually pretending to be German :)

Ah, prima. Dann können wir ja hier auf Deutsch weitermachen. Alex, das kommt Dir doch auch entgegen, oder? :D

**Comment by animaux** [comment]
> Ah, prima. Dann können wir ja hier auf Deutsch weitermachen. Alex, das kommt Dir doch auch entgegen, oder? :D

Jaaaa!

**Comment by animaux** [comment]
Ahh, da liegt dann wohl der Hase im Pfeffer:

If I pretend to be an englishmen in New York (Symphony set to english) and still have `'weekoffset' => '1',` all is well. Setting Symphony to »German« messes up the Weekday.

**Comment by animaux** [comment]
Which makes me wonder why Brendan is able to see things properly through his german-goggles?

**Comment by nilshoerrmann** [comment]
A few tests:

- English locale (no localisation), weekday offset `1` to `7`: correct headers, correct start of year.
- German locale, weekday offset `1` to `7`: correct headers, all days one day off (`-1`)

**Comment by nilshoerrmann** [comment]
This also happens with no offset at all (even if I comment out the setting for CLDNR). So my guess is, this is a Moment issue. 

This reminds me of a problem I discussed with @nitriques earlier on, where Moment converted `2015-01-01T00:00` German time to `2014-12-31T23:00` because of the timezone offset. If calendar works with UTC internally, this will cause the offset we see here. Maybe Nicolas has some ideas in this context.

**Comment by animaux** [comment]
No I begin to understadn why the Space Shuttle was never allowed to be in space during new year’s eve …

**Comment by nilshoerrmann** [comment]
Read the "Cause of Failure" section [here](http://en.wikipedia.org/wiki/Mars_Climate_Orbiter) and you'll see that things can even get worse …

**Comment by animaux** [comment]
Did read that a while ago. Expensive lessons learned … :)

**Comment by nitriques** [comment]
> Are we double handling?

Well I think so. I'll check to see if localization can be disable client side: we will use Symphony's locale info all the way, not mixing it with the browser's locale.

**Comment by nitriques** [comment]
After reading a lot on the topic, I think the safest thing would to alter the current locale.

http://momentjs.com/docs/#/customization/

**Comment by brendo** [comment]
We are doing that at the moment (heh), [right here](https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L30). I'm still haven't figured out quite where we are going wrong yet.

From what I can see, we set the locale, and Moment automatically bundles in the [`dow`](http://momentjs.com/docs/#/i18n/changing-locale/). The calendar docs seem to state that we don't need to set the weekOffset in this case because it'll be derived from the Moment locale.

**Comment by nilshoerrmann** [comment]
Brendan, the weekoffset works. The calendar itself is not built correctly.

**Comment by animaux** [comment]
@nilshoerrmann der frühe Vogel hat Junge :)

**Comment by nilshoerrmann** [comment]
@nitriques: Remember that I initially added the the timezone offset to the date before rendering the calendar in order to make sure that we didn't shift one day back in time for timezone that are ahead of UTC/GMT? That didn't work for you (you are 5 hours behind GMT) but it did for German time (GMT+1). This is what we have to look at to fix this issue.

- There is either a bug in Moment that causes this issue.
- Or – more likely – a misconfiguration on our side that makes Moment do this miscalculation.

**Comment by nilshoerrmann** [comment]
And just to point this out again: The **weekday offset** requested by Alex **works as expected**.
We are actually dealing with a bug **in the general calendar rending depending on the user's timezone**.

**Comment by nilshoerrmann** [comment]
I took a deeper look into this issue this morning:

1. The calender displays correctly, if we either don't set a locale _or_ if we "normalise" all dates to UTC by adding the timezone offset manually.
2. The calendar only works in localised environments as long as we set a locale because otherwise non-english month names are not recognised and the dates cannot be parsed.

So the easiest fix to just not set a locale is not applicable. 
Normalisation caused some trouble, too, as Nicolas reported when I started working on this feature (I couldn't find the related comments though).

What we could try is to only set the locale when needed and reset it right afterwards. 

Correct locales are needed in the following circumstances:

- when parsing a given date from the input (on load)
- when setting a new date to the input
- when creating the weekday headers
- when switching month in the dropdown

The English locale (or a date without timezone offset) is needed for:

- building the calendar sheet on load
- building the calendar sheet after switching months or years

**Comment by nilshoerrmann** [comment]
A few random thoughts:

1. Symphony's date field does not use timezones. If I enter `11:00` in Germany, it will be displayed as `11:00` in Australia as it will in Canada, too.
2. JavaScript always take the local time into account – so does Moment.
3. Because the one doesn't care about timezones (Symphony) while the other does (Moment/JS), we are running into problems.
4. Midnight seems to be the base time for the calendar generation which is why January, 1st is treated as December, 31st (`2015-01-01T00:00+0100 = `2014-12-31T23:00UTC` – different day).
5. If dates are converted to UTC internally by the used libraries, only timezones ahead of UTC can run into trouble (`2015-01-01T00:00-1200 = 2015-01-01-T12:00UTC` – same day).
6. We need to find to make the calendar always default to UTC without taking timezones into account (conversion)

**Comment by michael-e** [comment]
> Symphony's date field does not use timezones.

For my understanding: Doesn't it use the system timezone? Why else would it save two values?

**Comment by nilshoerrmann** [comment]
Actually, Symphony shouldn't store two values in my eyes: if you know the timezone, everything else is pure math. But as far as I'm aware, Symphony doesn't change the time display if the system timezone is changes.

**Comment by michael-e** [comment]
That's wrong. At least in the backend, time does actually change if I change the timezone in the config file.

**Comment by nilshoerrmann** [comment]
I didn't know that. Still, things seems to be a bit messed up conceptually:

- There still shouldn't be a need to store the date twice in the database.
- If Symphony takes the timezone into account when displaying dates in the backend, the date field has to make that information available in the markup.
- Currently neither the backend scripts nor the user knows anything about the used timezone.

**Comment by nilshoerrmann** [comment]
@brendo: 

**Let's remove the calendar from the 2.6 release completely**. 
All related code can be moved to a dedicated `calendar` branch. Let's do the following that branch:

- Decide how Symphony should handle timezones.
- Fix the data storage.
- Fix the date and time display (including the calendar).
- Only enable the calendar by default for the filtering, leave the field display to extensions.
- Decide whether the date field (independend of the calendar) should display the timezone in a small label (maybe offering a way to switch to a different timezone) or not.

This feature can then be merged for **Symphony 2.7**.

**Comment by animaux** [comment]
> Let's remove the calendar from the 2.6 release completely

:scream:

**Comment by nilshoerrmann** [comment]
Sorry, Alex, I think this is the only responsible decision.

**Comment by animaux** [comment]
:sob:

**Comment by jensscherbl** [comment]
> Sorry, Alex, I think this is the only responsible decision.

Agreed. I'd really like to have the calendar, but even more I prefer a stable release over buggy new features.

**Comment by nilshoerrmann** [comment]
I already create a [`calendar`](https://github.com/symphonycms/symphony-2/tree/calendar) branch and will prepare everything else later today or tomorrow.

**Comment by nilshoerrmann** [comment]
There are now two pending pull request:

- #2325 that removes the calendar for Symphony 2.6 and
- #2326 that adds it again for Symphony 2.7

**Comment by brendo** [comment]
This is the safest and fastest way to a 2.6.0 release, so I'm in favour of the `calendar` branch. 

Symphony supports timezones and the date field saves two values for as long as I can remember. The `value` is just a string which includes the timezone set in the Symphony configuration. The `date` is the UTC timestamp. We use this for filtering. We could exclusively use it. There was a reason why we don't exclusively use it, but it alludes me at the moment.

**Comment by brendo** [comment]
Thinking further. If the only reason this is being pulled is timezone, then this can be easily solved by adding a data attribute `data-utc` and use `$data['date']` or by making a call to `DateTimeObj::getGMT($value)`.

From my limited understanding of [the Calendar](https://github.com/symphonycms/symphony-2/blob/integration/symphony/assets/js/src/symphony.calendar.js#L19) script, this line would need to be changed to reference the UTC value and away we go.

**Comment by nilshoerrmann** [comment]
No, that wouldn't work due to the dynamic way JavaScript interacts with timezones.
I have an idea how to fix this and can work on this if you give me one or two weeks – but we shouldn't delay the 2.6 release any further because of this.

**Comment by nitriques** [comment]
> We are doing that at the moment (heh), right here. I'm still haven't figured out quite where we are going wrong yet.

This line is a problem since it already modifies the weekday offset...

Sorry that I missed so much on the last days, I have been terribly busy. Please never hesitate to ping me on twitter for urgent/pressing needs as I do not read emails from github since they make notifications disappear on the site.

**Comment by brendo** [comment]
I think I've solved this in 57fda1f. The key is to use the `daysOfTheWeek` provided by CLNDR instead of trying to iterate and build the titles ourselves.

**I think we should remove the `weekOffset` configuration option**. The calendar will use the locale information to determine what the starting day of the week should be. If you're running a German install, it'll be Monday. If you're running an English install, it'll be Sunday. 

This _appears_ to be the only way to support this functionality without getting into a mess. CLNDR strongly warns against mixing `weekOffset` and `daysOfWeek` configuration values when you are using moment to set the locale. It's an all or nothing affair. Should we want to support arbitrary week starts that are totally separate from your locale, we would have to override these values ourselves. This means provide the `weekOffset` (which is easy enough), and also provide the `daysOfTheWeek ` array (possible to retrieve from the Moment locale information).

I don't think we should go down that route. How often is this an actual requirement to change the starting day of the week away from your locale standard? Seems incredibly rare and it would be uncharacteristic of the core to handle.

Have I missed anything? If there are no objections, I'll go and remove the `weekOffset` setting from the remainder of the codebase and close #2312. This means #2325 and #2326 can be closed too.

**Comment by nilshoerrmann** [comment]
> I think I've solved this in 57fda1f.

Yes, you did.

> If there are no objections, I'll go and remove the weekOffset setting from the remainder of the codebase and close #2312. This means #2325 and #2326 can be closed too.

Go for it!

**Comment by jensscherbl** [comment]
> The calendar will use the locale information to determine what the starting day of the week should be. If you're running a German install, it'll be Monday. If you're running an English install, it'll be Sunday.

I'm usually running an English (language) install with German locale settings for date and time. How will it behave in such a case?

**Comment by nilshoerrmann** [comment]
First day of the week will be a Sunday.

**Comment by jensscherbl** [comment]
> First day of the week will be a Sunday.

Mhh. Not what I hoped for, but I guess clients can live with that.

Thinking about it, I don't even use any specifically German settings other than the timezone. It's pretty much all ISO standards. [ISO week date][1] says `Weeks start with Monday` by the way... ;)

[1]: http://en.wikipedia.org/wiki/ISO_week_date

**Comment by nilshoerrmann** [comment]
> ISO week date says Weeks start with Monday by the way …

Haha, remember this is JavaScript not ISO ;)
It's a mess …

**Comment by nilshoerrmann** [comment]
There are two options to work around this issue:

1. You can set the Symphony language to German and switch back to English in your own profile.
2. You can fool Symphony, if you'd like to have the backend in English but with German dates: Just create a German localisation extension that doesn't provide any translations. The month names in the widget will be German in this case though because those translations are provided by Moment directly.

**Comment by jensscherbl** [comment]
> There are two options to work around this issue

Thanks. Will see what works best...

**Comment by brendo** [comment]
Closing down, thanks for everyone's input!
