### ISSUE TITLE
JavaScript code in Input fields gets executed in the backend

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2318]
Using Symphony 2.6.0-beta.2, I noticed a potential vulnerability. In the backend, an author can save JavaScript code which gets executed when another author hits a section's index page.

Steps to reproduce:

* Create section "Test1"
* In section Test1, create an Input field called "Title"
* Create section "Test2"
* In section Test2, create an Input field called "Title"
* In section Test2, create an SBL field called "SBL" and choose "Title" from section "Test1" in the "values" selector. Check "Display in entries table", then save.

Now add data:

* In section "Test1", create an entry using the title  
    `<strong>This is a test</strong><script>alert('uh-oh');</script>`
* If you click on "Test2" (from the "Content" Menu) in order to add content to this section, you will see that the script already gets executed on the empty index page.
* Now add a new entry called "Test" to section "Test2". In the SBL you have an interesting option:  
    `<strong>This is a test</strong><script>alert('uh-oh');</script>`  
    Choose it, then save the new entry.
* Go back to the index page of this section. You will see that the script now gets executed twice on page load. You will also find that the SBL field's value "This is a test" is displayed **strong**.

So in this scenario all HTML seems unescaped.

**Comment by michael-e** [comment]
I tracked it down to [this SBL commit](https://github.com/symphonycms/selectbox_link_field/commit/51db3646b5f9523e7b5fe4fd965d17e9f20e0324).

**Comment by twiro** [comment]
> _I tracked it down to this SBL commit._

Funnily enough that single "else"-statement already caused [quite some trouble](https://github.com/DeuxHuitHuit/multilingual_field/issues/60#issuecomment-52423253) in combination with the multilingual field...

**Comment by nitriques** [comment]
@twiro Indeed.

But @michael-e Doing the same thing in a markdown enable text box would give the same result...

**Comment by michael-e** [comment]
You mean a textarea with Markdown? Nope, that is no prob. On the index page it displays `This is a testalert('uh-oh');`, just like the original Input field does. The problem is with the SBL's `Display in entries table` functionality.

**Comment by jensscherbl** [comment]
> In the backend, an author can save JavaScript code which gets executed when another author hits a section's index page.

Holy shit... oO

**Comment by brendo** [comment]
This is bad. The fix will likely be in the SBL to sanitise the data, even if the field won't.

**Comment by michael-e** [comment]
Obviously all SBL versions >1.29 are affected. So when this is fixed, we should tell people to update the SBL extension if they are on Symphony 2.4+.

**Comment by michael-e** [comment]
Here is the commit with the problematic code inside the else clause: https://github.com/symphonycms/selectbox_link_field/commit/98ba905f9edb780dd37ef4379ec9ef52d7a911a2

**Comment by nitriques** [comment]
> On the index page it displays This is a testalert('uh-oh');

Yeah but in your DS you'll get the full html, script tag included.

Indeed good find @twiro.

**Comment by brendo** [comment]
Right so here's a brain dump of me looking at this today:

The commit [in question](https://github.com/symphonycms/selectbox_link_field/blob/51db3646b5f9523e7b5fe4fd965d17e9f20e0324/fields/field.selectbox_link.php) that introduced this issue was trying to achieve the following logic.

1. When attempting to generate all the possible values (`findRelatedValues`) for this Select Box Link...
2. Ask the Field(s) that the SBL is linked to, to format each entry in the linked Section so it can be displayed in the SBL select box...
3. First prefer an 'unformatted' value, then prefer the 'raw' value, otherwise we'll just have the value that the Field gives the parameter pool...

Now, `findRelatedValues` is used in multiple contexts:

1. Formatting the value for `appendFormattedElement` (that is the Datasource XML)
2. Formatting the value for `prepareTableValue` (that is displaying it on the Publish Index in the Symphony backend)
3. Formatting the value when the SBL is the 'heading' of the entry 
4. Exporting the Field data in `prepareExportValue` (usually so it can be 'imported' again)
5. When generating all the possibles values of the SBL and displaying it inside a Select Box via `findOptions`, so this is:
    - With Selected menu on the Publish Index (`getToggleStates`)
    - When creating/editing an entry (`displayPublishPanel`)

So the challenge is getting the appropriate value for the right context.

- For the Datasource XML, we likely want a safe value that we can directly output, we use `General::sanitize` at the moment to do this.
- For the Publish Index rows, we want a value that an Author can understand, so we'd probably like a safe value here too. When HTML is thrown into the mix, we'd probably prefer it was stripped (I can't say I overly encourage coupling templating and values together, but anyway)
- For the heading scenario, we want a safe value that makes sense
- For exporting the Field data, we probably want the exact value. This prevents a chinese whispers problem where the exported data doesn't know the full picture.
- For displaying the possible values, we want a safe value that is going to make sense in a Select Box. Select Boxes don't accept HTML so it should be totally stripped.

Based off that, the only time we probably *don't* want to sanitise the output is during export, so we should appear `General::sanitise` in the main `findRelatedValues` function, safeguarding the entire system from whatever this value may be. For export? There's a handy `General::reverse_sanitize` function that could help.

Does anyone see any problems with this approach?

**Comment by brendo** [comment]
Proposed fix pushed to the SBL repo

**Comment by michael-e** [comment]
Confirmed that it solves the issue.

**Comment by andrewminton** [comment]
Would this also effect the Association field maybe?

**Comment by michael-e** [comment]
@andrewminton, can you test this? I am not using the Association field (because still it has not been marked as "the way to go", AFAIK).

**Comment by andrewminton** [comment]
Will do.

**Comment by nitriques** [comment]
> Formatting the value for prepareTableValue (that is displaying it on the Publish Index in the Symphony backend)

Why not try prepareTextValue before ? it should already be "clean"
