### ISSUE TITLE
Cookie gets set on 404 responses

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2357]
On successful responses (status 200) Symphony does not set cookies if it is not necessary (i.e. if there is no session data).

But when a 404 response is sent by Symphony, there will be a cookie set. The corresponding response header will look like:

    Set-Cookie: PHPSESSID=328obld6vdphsqndsgf5bt34o5; expires=Sat, 07-Mar-2015 09:24:59 GMT; path=/; HttpOnly

You can test this in a terminal window using `curl`:

    curl -I http://example.com/non-existent-page/
 
I verified this issue with the latest integration code and an older Symphony 2.3.6 install — so obviously this behaviour is not new.

**Comment by michael-e** [comment]
I should add that the cookie gets set no matter if you use a dedicated 404 page or Symphony's generic error page.

**Comment by nitriques** [comment]
Hum that's not cool. Will check.

**Comment by brendo** [comment]
Interesting. This is likely because a 404 is raised as an Exception, and thereby handled by the error handler, not the usual launcher. The usual launcher has some code to cleanup cookies and the like, whereas the exception handler does not. It simply outputs the header and exception content.

All fixed now.

**Comment by michael-e** [comment]
Confirmed, thanks a lot!

**Comment by nitriques** [comment]
Great!
