### ISSUE TITLE
Date Field: Is the "date" column ever needed?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2360]
There have been many changes to the Date Field in the past, and I admit that I lost track at a certain point.

At the moment I try to save birthdays to a date field, so I use the date field without time. I noticed that — in addition to the ISO date — there is a second column called "date" in the Date Field's database table. With UTC+1 as my timezone I see rows like this in the database table:

    6012    13627    1970-02-16T00:00:00+01:00    1970-02-15 23:00:00

I wonder if that "date" column is ever used by the date field. What is the sense behind it? If it makes no sense, why is it there?

(Related question: Is it a wise decision at all to save birthdays using a Date Field?)

**Comment by nitriques** [comment]
> Related question: Is it a wise decision at all to save birthdays using a Date Field?

I think it clearly is.

Maybe @nilshoerrmann knows why... (?)

**Comment by michael-e** [comment]
I thought about it, and I think it is a bad idea. If I would try and save "date and time of birth", a date field would be perfect. But the _birthday_ is something different. Here's a simple example: You are born in Paris on December 12, let's say at 2 o'clock a.m. At that point in time it is December **11th** in New York. Still, if someone form New York asks for your birthday, you would say "December 12", right? So "date and time of birth" (a date, technically) and "birthday" (never "localized"!) are two completely different things.

Still I wonder what this database column is about. :-)

**Comment by nilshoerrmann** [comment]
The second database column is there for historical reasons and it has been proposed to remove it in another thread.

> You are born in Paris on December 12, let's say at 2 o'clock a.m. At that point in time it is December 11th in New York. Still, if someone form New York asks for your birthday, you would say "December 12", right? So "date and time of birth" (a date, technically) and "birthday" (never "localized"!) are two completely different things.

Symphony always returns system times (based on the timezone specified in your config) so this won't be a problem as long as you don't convert dates to different timezones yourself (in JavaScript for instance).

I'd use a date field for the birthdays – otherwise you want be able to filter by dates (or use date comparisons in your DS).

**Comment by nitriques** [comment]
Well, from a DB PoV, you would set in in a date column, without any notion of time/timezones.

In Symphony, I would still put it in a datetime field and consider it to be timezone-less.

**Comment by nilshoerrmann** [comment]
PS:

> There have been many changes to the Date Field in the past, and I admit that I lost track at a certain point

These changes have been UI related – the data storage hasn't changes over the last years.

**Comment by michael-e** [comment]
> Symphony always returns system times (based on the timezone specified in your config) so this won't be a problem as long as you don't convert dates to different timezones yourself (in JavaScript for instance).

Oh, in my eyes it will be an issue! If I save a birthday as `1980-12-12T00:00:00+01:00`, then change Symphony's timezone from "Europe/Berlin" to "Europe/London", this date will be output as `1980-12-11T00:00:00+00:00`, so my templates will display one day off (unless I do date calculations in my output templates).

Fortunately, filtering on thise birthdays will be done in Elasticsearch anyway (on indexed custom values composed of month and day, because I don't want to use the year). So I can choose any data type I like in Symphony.

**Comment by nilshoerrmann** [comment]
If you always store the birthday with 12:00 as time, there shouldn't be a day shift when you change the system timezone.

**Comment by michael-e** [comment]
As long as my system timezone is Europe/Berlin, I would have to use 13:00 as time, and I would have to change this suffixed time if I change the system timezone. Anyway, saving a _birthday_ as (localized) date/time feels technically incorrect, see above.

**Comment by nitriques** [comment]
@nilshoerrmann I have been tempted to add a timezone field setting in DateTime for quite sometimes now. By default, I would be the one configured by Symphony.

Michael would then be able to set his birthday as UTC and always treat it as such. MySQL handles timezones OK I guess.

**Comment by michael-e** [comment]
If at all, the date field (or even better, a different field?) should have the ability to save a date that is never localized (i.e. has no timezone in effect at all). But there wouldn't be a big difference then from saving a string—apart from being able to use different formats for manual input.

**Comment by nilshoerrmann** [comment]
You can pass a timezone to the date field along with the date and time, e. g. GMT.

**Comment by michael-e** [comment]
I do not think that any timezone logic is suited well for a birthday (and so the Date Field can not be the right choice). I will give you another example: Imagine that someone living in London (GMT+00:00) is on holidays in Asia, but he was born in Australia. At which time do you think should he start celebrating his birthday? I would say: 00:00 local time, no matter where he was born or where he normally lives. We see that the "birthday" value is treated as a string value by human beings, which never changes if you switch timezones. (Any real date/time value does change, of course.)

**Comment by nitriques** [comment]
Michael I agree with your theory. Also, DB can use not localized date time storage. Oracle even as a date (without time) type.

But in Symphony, do you really need this ? I mean, your birthday field will always be birthdays... setting it to UTC as no-localized would be sufficient IMO. It will always be like a non-localized version, no ?

**Comment by michael-e** [comment]
So what do you suggest? Add functionality to the date field to output non-localized dates?

Well, we have a setting called "Display time"… Has this intended to do non-timezone stuff, maybe? What exactly do we expect if time is not displayed in the backend?

I will come back to this tomorrow or the day after tomorrow, it's already late here.

**Comment by nitriques** [comment]
> So what do you suggest? Add functionality to the date field to output non-localized dates?

Yeah, but non-localized dates in PHP does not exists. They are UTC or system defined. Moment.js treats non-timezoned values as UTC and keeps a private flag to know it does not have a valid timezone....

We could use MySQL DATE type, but that would only impact the storage size and sorting operations.

> Well, we have a setting called "Display time"… 

This is meant purely as a UI feature, i.e., display time in both publish views.

That's why I though about a Timezone setting. Or we could use MySQL type in order to "forget" about php's timezone...

I am open to ideas :) And you know Michael how I love to argue with you :)

**Comment by nilshoerrmann** [comment]
I have to admit that in my eyes this is a purely theoretical or philosophical discussion:

- As long as you don't plan to move your system to the international dateline, you are save with the date field because the timezone offset will never cause a day shift as long as you stick to noontime. As both, the server (PHP) and the browser (JavaScript), always require a timezone for dates, you will have to agree on a standard timezone for "timezone-less" date information, if you like to make use of the build in date and time features of both sides. Using GMT/UTC as default seems to be common practice.
- If you don't need any build in date and time functionality – neither in the backend nor on the frontend – you can just save a plain date string in the format of `YYYY-MM-DD` and you will be able to parse that using XSLT. Of course, you could create a timezone-less date field but I don't see a need for it, if a normal input field does the job already.

The most important thing is that you as the developer of a site or an app are aware of timezones and related day shifts. You just have to figure out _your way_ to stop day shifts for birthdays. And in Symphony, this can either be achieved by a standardized timezone values on the date field (used for input and output) or by not storing values as `datetime` but as `text` as thus using an input field. 

I don't think that the date field needs to be adjusted to handle this. 
It would just overcomplicate things because it means working against the system.

**Comment by nilshoerrmann** [comment]
And just to make this point clearer: it's either you who agrees on a default timezone or a "timezone-less" field that does this under the hood without anyone noticing.

**Comment by nitriques** [comment]
> I have to admit that in my eyes this is a purely theoretical or philosophical discussion

Yes you are right!

**Comment by michael-e** [comment]
> I have to admit that in my eyes this is a purely theoretical or philosophical discussion

Yep. But when I started it, I had more questions than answers. :-)

> I don't think that the date field needs to be adjusted to handle this. 

That is my feeling as well. Either I create a new field called "Birthday Field" or I go with a simple Input Field. As I said, Symphony's internal (field) sorting capabilities are a non-issue for me, because I use Elasticsearch anyway.

The main point of my original post was the database column, and [Nils pointed out](https://github.com/symphonycms/symphony-2/issues/2360#issuecomment-76220694) that it is a relict of the past. So I may open another issue saying "remove that column".

Thanks to everybody for the instructive discussion!

**Comment by nitriques** [comment]
> Thanks to everybody for the instructive discussion!

You're welcome! And thanks to you too :)

**Comment by nilshoerrmann** [comment]
@michael-e: My guess is that you need that for the app we both know. As you run Elasticsearch in the background, I'd use an input field with a custom validation rule for your favourite date format. You could also extend the output field, if you need special attributes in your XML: it just extends the default input field's output, see https://github.com/hananils/output_field/blob/master/fields/field.output.php#L31.

**Comment by michael-e** [comment]
Thanks, @nilshoerrmann. Yes, it's the crazy app. :-)

> I'd use an input field with a custom validation rule for your favourite date format

That's what I will probably do.
