### ISSUE TITLE
Delegate tracking a delegate

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2366]
Is there any way we can have one delegate know if another has fired? I'll explain, as that sounds weird...

I want to track all the SQL statements that are run for say, a Section save event (create/edit/delete delegates). I know there is the delegate that fires for each SQL statement, but at that point there is no context as to what called it, so I can't say "Ah, this group of SQL statements are from a Section being created!".

The same for Entries and other perts of the system too.

**Comment by nitriques** [comment]
> Is there any way we can have one delegate know if another has fired? 

Yes, a simple array could do the trick... :)

> "Ah, this group of SQL statements are from a Section being created!".

This is waaay trickier. By knowing which delegate got called, how would you deduce this ?

**Comment by designermonkey** [comment]
Our delegates system is too clunky. A better system would be one that used event triggering.

An extension could listen to two events (pseudo example here):

- `section.before.create` - Where it starts to listen to `database.query` which emits it's SQL among other things.
- Listening to the `database.query` event allows the extension to gather the SQL queries.
- `section.after.create` - Where it stops listening `database.query` and processes the gathered results.

Obv, this is not possible in the current version, at least I don't think so?

**Comment by designermonkey** [comment]
Hmm, yeah, we don't have a central place for runtime delegate attachments, which is the clunky part I was on about. It's a shame.

**Comment by nitriques** [comment]
Yeah delegates and events are two different beasts.

We currently use "automatic event registration" (registration is done once and cannot be undone)

Maybe it's a separate feature ?

**Comment by designermonkey** [comment]
I suppose it boils down to how the extension is instantiated during runtime.

Is the extension instantiated only once, or does it happen on a per delegate triggering basis?

**Comment by nitriques** [comment]
Event registration can typically occur anytime after the creation of the event source...

Right now, I think we check the pool of listeners only when the actual delegate is called.

**Comment by brendo** [comment]
Could it be solved by subscribing to SectionPreCreate and PostCreate delegates and then calling `Symphony::Database()->debug()` to get the list of queries that have run? We do something similar in `ExtensionManager->notifyMembers` to find out what extension ran which queries. Alternatively, you can subscribe to `PostQueryExecution` and use some sort of timestamp to figure out what has run. 

> Is the extension instantiated only once, or does it happen on a per delegate triggering basis?

Once. Extensions are initialised once and saved into a static cache. The `ExtensionManager` is a singleton.

> Right now, I think we check the pool of listeners only when the actual delegate is called.

Correct, the subscriptions are loaded on initialisation of the `ExtensionManager`, but we only check the subscriptions for matching listeners when the delegate is fired.

----

Given the delegate system was built nearly 10 years ago, it's definitely got it's flaws. Unlike modern event dispatcher's featured in Symfony2 or Laravel, the Symphony Extension Manager delegate system is immutable out of the box. Extensions register their events (delegates) when they are installed (tbl_extensions_delegates) and the Extension Manager uses these on each page load. 

A more modern solution would be to decouple the delegates from the Extension Manager, allowing extensions and the core to be equal citizens. A central event dispatcher would allow both extensions and the core to listen to delegates. It's crazy at the moment that sometimes extensions have more power than the core because of the delegate system!

**Comment by designermonkey** [comment]
I like the `debug` idea!

Also, as the extension is initialised once, this means (correct me if I'm wrong), one delegate callback can affect the extension by adding say a cache, and a later callback can read it?

**Comment by brendo** [comment]
> Also, as the extension is initialised once, this means (correct me if I'm wrong), one delegate callback can affect the extension by adding say a cache, and a later callback can read it?

Yes, this is how the Expression/Reflection Field does it's magic. One delegate sets a static variable on the extension, and then later in the lifecycle another delegate reads from that variable. It's not a 'modern' way of doing it, but it can work for the moment.

**Comment by brendo** [comment]
Closing...
