### ISSUE TITLE
Sort column while filter is active

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/symphony-2#2465]
Sorting a column while a filter is active is removing the last character of the filter from the URL after the sort is applied.

**Comment by nitriques** [comment]
I am not able to reproduce... Could you give me the url (without the domain) have on the sort anchor element ?

**Comment by nitriques** [comment]
I do not understand why both 7328c19a5 and 4631a4371 used `trim($params['filters'], '&amp;');`

AS per php's doc:

> character_mask
> Optionally, the stripped characters can also be specified using the character_mask parameter. Simply list > all characters that you want to be stripped. With .. you can specify a range of characters.

Sooooo, the '&amp;' will trim any of those letters, regarding of their order in.

I did this test

```php
var_dump(trim('aa', '&amp;'));die;
```

and got an empty string back. I did my test with 'sasasasa', which, by luck, ends with one of those 5 chars.

@designermonkey must have log the bug because of the same reason, and it never got fixed cause it was working for most of the inputs. This is beautiful.
