### ISSUE TITLE
 mysqli_query(): (21000/1242): Subquery returns more than 1 row

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2469]
and ds error looks this way:

<img width="684" alt="screen shot 2015-07-17 at 22 06 20" src="https://cloud.githubusercontent.com/assets/2312755/8754977/1a7884be-2cd0-11e5-9d96-0f6cc9d3fc02.png">

<img width="984" alt="screen shot 2015-07-17 at 22 04 40" src="https://cloud.githubusercontent.com/assets/2312755/8754966/f50e24d6-2ccf-11e5-8f18-7810f61b7a77.png">

**Comment by nitriques** [comment]
I think this is a LSE bug, not a core bug. Which fields to you have in that section ?

**Comment by cmnstmntmn** [comment]
it was a dupe on **entry_id** field; i had search and delete one of them.
somehow, i experienced the same [issue](http://www.getsymphony.com/discuss/thread/91954/) as vlad

**Comment by cmnstmntmn** [comment]
these are the fields of that section

<img width="321" alt="screen shot 2015-07-17 at 23 31 52" src="https://cloud.githubusercontent.com/assets/2312755/8756576/0b66dabe-2cdc-11e5-9d61-0764e776814e.png">

**Comment by nitriques** [comment]
Yeah, I've run into that problem many times before. See #2401

**Comment by michael-e** [comment]
It was the Textbox field, right? It looks as if [it has not been fixed](https://github.com/psychoticmeow/textboxfield/blob/master/fields/field.textbox.php#L45) similar to other fields. The line in question should actually be:

    UNIQUE KEY `entry_id` (`entry_id`),

This should fix your the main issue of having non-unique entry IDs.

(Given the fact that this extension experienced not a single commit for two years now, I personally wouldn't rely on it at all. Some day we should really start whitelisting/blacklisting extensions.)

**Comment by nitriques** [comment]
> It was the Textbox field, right

Yeah but other fields [have similar problems](https://github.com/DeuxHuitHuit/multilingual_field/commit/ce608240978026da3c162745f49f68a0033be567).

**Comment by brendo** [comment]
Closing as this isn't a core issue.

**Comment by twiro** [comment]
> _(Given the fact that this extension experienced not a single commit for two years now, I personally wouldn't rely on it at all. Some day we should really start whitelisting/blacklisting extensions.)_

@michael-e : I guess the main problem with textbox-field is not that it's not maintained, but that the maintained version isn't promoted anywhere.

[Symphonyextensions](http://symphonyextensions.com/extensions/textboxfield/) only lists @psychoticmeow's [repo](https://github.com/psychoticmeow/textboxfield), that in fact hasn't been updated for more than two years. But there is a [symphonists-fork](https://github.com/symphonists/textboxfield/commit/a8ab151d9839a84c0b0313b74be03aa1da3a4d7a) that has been:

The bug described above (duplicate entries in database) has been [fixed by brendo in version 2.3.4](https://github.com/symphonists/textboxfield/commit/1f33d232c61e593c9de3beeb1a804f2bdc0d67be
) more than a year ago.

And there has been a [2.4.0-release with other fixes](https://github.com/symphonists/textboxfield/commit/a8ab151d9839a84c0b0313b74be03aa1da3a4d7a) less than a year ago.

It would be great to have the actively maintained repo listed on symphonyextensions (and [linked in the multilingual field repo](https://github.com/DeuxHuitHuit/multilingual_field/blob/master/README.markdown#1-about) that extends textbox).

So the first thing that should be decided is if the symphonists-repo should officially be promoted/linked instead or rowans repo. @psychoticmeow, @brendo,@nitriques - thoughts on this?

**Comment by psychoticmeow** [comment]
Yes it should, but I can't do it because the site doesn't work since I changed my name on GitHub. So manual intervention will be needed.

**Comment by brendo** [comment]
@nickdunn @allen This has come up a couple of times recently, and there's a few odd jobs stacking up on Symphon Extensions. Who has the keys to the site these days, and can I borrow them?

**Comment by nitriques** [comment]
@twiro Yes we have some cleanup to do on Sym Ext. But I do not have any access to do it (which I'd like to get...)

**Comment by allen** [comment]
The symphonyextensions site is currently being handed off from Nick to our server environment. I've done the last few tasks that @nickdunn has asked me to do to get the new server up and running. Nick just have to change across the DNS settings and the new server should be in working working order. Anyone that has access to the symphony hosting repository will have access details to the server.

**Comment by brendo** [comment]
Thanks @allen!

**Comment by twiro** [comment]
Thanks for the feedback guys!

> _The symphonyextensions site is currently being handed off from Nick to our server environment._

Sounds good!

Symphonyextensions.com has proven immensely useful for me over the last years _(lots of thanks to @nickdunn who has done incredible work here)_ and as the main symphony website feels quite outdated regarding extension-listings (and a bit asleep in general) it would be of great benefit for the symphony eco-system to see that important resource up to date and actively maintained.

I guess a **separate issue tracker for symphonyextensions.com** would be of huge help when trying to improve quality of extension-listings, so would a symphonyextensions.com-repo on github make sense in your eyes? (wouldn't need to host the actual website-code there, but maybe that would make sense too regarding the current changes in maintenance for that website...)

Extension-developers could discuss all things related to extension-listings there instead of doing so in lots of different (and not that focused) communication-channels like the main symphony repo, the forum, twitter, gitter, etc. - and regarding @michael-e's proposal (_"Some day we should really start whitelisting/blacklisting extensions"_) - that would feel like a perfect place to discuss that kind of stuff and decide upon the state/usefulness of abandoned/deprecated extensions.

And an own repo could also be used for discussing general improvements regarding the extension-eco-system.

what do you think?

> _Yes we have some cleanup to do on Sym Ext. But I do not have any access to do it (which I'd like to get...)_

My vote for @nitriques getting write access :+1: 

Maybe [Extension Downloader](https://github.com/DeuxHuitHuit/extension_downloader) could get more tightly coupled with the symphonyextensions-site and promoted as tool of trade there. (Though it's not up to date right now, right?). And would be awesome to see this extended as a kind of **extension manager** that handles updates too... just dreaming :)

**Comment by nitriques** [comment]
> I guess a separate issue tracker for symphonyextensions.com

I vote for that !

> "Some day we should really start whitelisting/blacklisting extensions"

There's a deprecated status value, but in order to update it, we need write access to the repo...

> My vote for @nitriques getting write access :+1:

Thanks :)

> Maybe Extension Downloader could get more tightly coupled with the symphonyextensions-site and promoted as tool of trade there. 

It could !

> (Though it's not up to date right now, right?)

I am not aware for any bugs... could you [report them](https://github.com/DeuxHuitHuit/extension_downloader/issues) ?

**Comment by jensscherbl** [comment]
> (Though it's not up to date right now, right?)
>> I am not aware for any bugs...

Last supported Symphony version was [2.4.x][1].

[1]: https://github.com/DeuxHuitHuit/extension_downloader/blob/master/extension.meta.xml#L26

**Comment by nitriques** [comment]
> Last supported Symphony version was

It's just a matter of updating the xml file. I've used it with 2.6.x. Again, lazy (or forgotten).
