### ISSUE TITLE
MySQL::isConnection function - is the mysqli_ping required?

### ISSUE THREAD

**Issue by jmoont** [symphonycms/symphony-2#2471]
I am seeing the MySQL::isConnection function run 29 times in a page and using 67% of the time of that page load. Can you explain what the mysqli_ping does and if it is needed.

I have commented out mysqli_ping(MySQL::$_connection['id']) on line 260 of class.mysql.php and it seems to have no adverse effect on the system but does speed up the page loads.

**Comment by brendo** [comment]
`mysqli_ping` is used to help ensure the database connection remains up. [As per the docs](http://php.net/manual/en/mysqli.ping.php), it will automatically reconnect to the database server if the connection has gone flat. This helped resolved errors with 'MySQL Server has gone away' responses.

It's called frequently as each `Symphony::Database()->query()` will check run `isConnected()` to ensure the database is around. It's interesting you are experiencing slower speeds because of the ping though! Is your database local to the server? Or on a shared/external server? What version of PHP/MySQL is running?

**Comment by brendo** [comment]
Further reading from the docs states the reconnection only occurs in some scenarios:

> Checks whether the connection to the server is working. If it has gone down, and global option mysqli.reconnect is enabled an automatic reconnection is attempted.

By default `mysqli.reconnect` is set to `0` (don't reconnect) on Debian (from the comments) and as specified by PHP. On my local machine, it's set to `1` by default.

We may be better off inspecting this value on class startup and then conditionally referencing the `mysqli_ping()` method.

**Comment by jmoont** [comment]
I'm using a cloud database that isn't local to the server but on the same internal network.
Percona 5.6
PHP 5.5.9

In my php.ini:
mysqli.reconnect = Off

**Comment by jmoont** [comment]
More reading up on this and mysqli.reconnect isn't a recommended pattern
https://bugs.php.net/bug.php?id=52561

It is not implemented because reconnect creates a new connection which has new state and the state of the old connection is gone - session variables, transaction. In this context automatic reconnect is considered dangerous and is disabled since years in libmysql. mysqlnd doesn't provide this for the very same reason.

**Comment by brendo** [comment]
Great find! I'll remove the offending line from the `MySQL::isConnected` method, thanks!

**Comment by nitriques** [comment]
Great find @jmoont !!!
