### ISSUE TITLE
Data Source Filtering by System ID is broken

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2475]
In the current 2.6.x branch, data source filtering by System ID is broken: The datasource will return entries if you filter using `@` or `€` as values. The filter will not do anything in this case.

<img width="757" alt="bildschirmfoto 2015-08-04 um 20 34 35" src="https://cloud.githubusercontent.com/assets/40072/9069219/4a67cf56-3ae8-11e5-90a3-50531bf5fba0.png">

**Comment by brendo** [comment]
Logically, those values are not integers and are hence ignored, meaning the datasource will return as if no filter was applied. There is some [conflicting logic](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/data-sources/class.datasource.section.php#L395-L411) in the Datasource that's preventing this from working correctly though.

Nice find!

**Comment by brendo** [comment]
@nitriques It's the changes to `General::intval` that are causing an issue here. By returning -1, we can potentially get an awkward count value, and `array_filter` will no longer clean up the bad data. Since 0 is 'falsey', I'd almost propose `General::intval` should return `0` rather than `-1` because it's more useful.

**Comment by brendo** [comment]
Nevermind, that'd be a breaking change so we'll work around it for now. @michael-e, this should be restored to 2.5.x behaviour now :)

**Comment by nitriques** [comment]
>  I'd almost propose General::intval should return 0 rather than -1 because it's more useful.

Returning -1 is already how php handles "error" cases (array_search, strpos)...

Also, 0 *is* a valid int.

It's the same thing with php's empty calls: we sometimes just can't related on it, as we sometimes can't related on intval.

**Comment by michael-e** [comment]
@brendo: My datasources don't output anything now. I am rather sure that there are two mistakes in your commit:

1. The callback function needs to `return $val;`
2.  It should be written `function($val)` (without space in betweeen!)

If I do it like this, the datasources work again. But, unfortunately, the bug is still not fixed by this change.

**Comment by michael-e** [comment]
Checked it out. If I filter using `€`, the

    `e`.id IN ()

part is still missing in the DB query.

**Comment by brendo** [comment]
I can confirm that using `€` is totally removed from the filtering. It doesn't even reach the datasource because it's being stripped out and deemed as an [invalid filter](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.datasource.php#L309-L312) (#1759). This is probably wrong, `€` is not a 'normal' character, but it's still valid. The problem we were trying to solve in #1759 is removing bad filters like ` + ` or ` , `, so the regex should be that specific.

Once that bug is fixed...

> The callback function needs to return $val;
> It should be written function($val) (without space in betweeen!)

First one is a problem, thanks, second one doesn't matter, PHP isn't whitespace significant :)

I pushed a commit up which should resolve the issue now :)

**Comment by michael-e** [comment]
> second one doesn't matter, PHP isn't whitespace significant

Maybe I was fooled by some caching… :-) Sorry.

> I pushed a commit up which should resolve the issue now :)

Confirmed. Thanks!
