### ISSUE TITLE
XSLT-based backend

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2537]
As @michael-e [mentioned here](https://github.com/symphonycms/members/pull/274#issuecomment-167992404)

> The purely PHP-driven backend is the biggest shortcoming of Symphony

I think there had been some talking about this, but could not find in a quick manner the discussions / issues.
Are there any plans to make the Symphony backend XSLT-based?

Anyway, what's the labour with it?
- Create read-only system data sources?
- Update the backend pages / templating?
- "Cleanup" Symphony PHP classes?
- Update all of the extensions?

The list above shows how little I undestand these backend dev issues, but wanted to scratch the topic a bit at least.

Thanks.

**Comment by bernardodiasc** [comment]
Hello Juraj, as far as I remember, Nick Dunn made the REST API extension to temporary solve one need that should be a core feature. I think Wordpress did an outstanding work with https://developer.wordpress.com/calypso/ that is basically what was proposed for Symphony, build a solid API and build the Symphony backend upon it.

Not a PHP developer here, just summing up with this information. Cheers!

**Comment by michael-e** [comment]
I am not sure if this discussion makes sense. Indeed there has been a lot of talking about it, but I never found many friends. :-)

So @nitriques may simply close the issue if he feels that this is not a good topic.

Switching to an XSLT driven backend would mean a lot of work, and I am rather sure that most of the extensions would have to be re-written from scratch. This would really be a breaking change, and if it is ever done I would suggest to call it Symphony 4 (at least).

The biggest advantage: We could unify a lot of things that exist twice, mainly:

* logic to read/create/edit/delete entries
* user management (we have backend users and frontend Members)
* special PHP logic that can be built with events/filters

Regarding the main steps to take, at first sight you might be right. But if we think about pages, data sources and events, I think we'd be close to a proper API approach as mentioned by @bernardodiasc.

There would be a lot of pitfalls on the road. Think about data sources, for example. Is it best to introduce another abstraction layer (potentially inflexible), or is it best to use/allow straight SQL queries? Both?

Anyway I would suggest to simplify the backend. Some of the things which need complicated GUIs could be done simpler by editing files in the filesystem. Of course we'd have to find the right data formats, so developers wouldn't need a handbook to create a data source, for example. Dropping most of the GUIs would also save dev power, and it might lead to an even smaller, still more powerful system.

Another aspect of such a re-write: It could be possible to separate application data and dynamic data. Symphony is really hard to deploy because these get mixed up in the database.

For me this has been a dream since a long time, but: I am sure that this would mean a complete break if you want to do it right. It would mean to question averything and to design the system and the APIs before any coding takes place. Maybe we could use existing code in the end, maybe not.

**Comment by nitriques** [comment]
This is an old debate :) Haha. I am for it. 

> I would suggest to call it Symphony 4 (at least).

Yeah, Micheal's right.

And it was also already done in ["Symphony 3"](https://github.com/symphonycms/symphony-3/blob/master/symphony/content/publish/publish.xsl)

But 

> build a solid API and build the Symphony backend upon it.

That's the mid-term goal. We already talk in depth about abstracting the render layer and diving into the PHP ecosystem with composer. Once we have that, it could be a could idea to create unit and integration testing too. I'd very like to this in a retro-compatible way too. Once the code base is safer to play with, rebuilding the backend would then be much easier. 

I will close the issue for now, but rest assured: it won't go away :)
