### ISSUE TITLE
getenv() not preferred over $_SERVER due to varying host implementations

### ISSUE THREAD

**Issue by neosatus** [symphonycms/symphony-2#2569]
I started setting up Symphony for the first time today on my host, NearlyFreeSpeech. Everything went smoothly until it came time to login to the admin panel. First, no CSS was loading and second, upon logging in, the domain dropped off the url and my url bar only held /admin/login. Mousing over the "retrieve password" link verified that the domain variable was null.

The domain variable is set in /symphony/lib/boot/defines.php and uses getenv('HTTP_HOST') to get the domain. However, NearlyFreeSpeech doesn't pass HTTP_HOST to the Environment. I was able to get it working by hard coding a setenv call at the top of index.php. 

I had also made a post on my host's support forum about the issue and they advised never to use getenv() over $_SERVER for precisely the issue I ran into today: some hosts don't pass all of the $_SERVER variables into the environment. The developers in the chat seemed to think it was worth considering ditching getenv() for $_SERVER in all cases and asked me to write this issue report.

**Comment by michael-e** [comment]
Thanks for posting. I think we should seriously consider using the `$_SERVER` superglobal everywhere.

**Comment by nitriques** [comment]
>  I think we should seriously consider using the $_SERVER superglobal everywhere.

I do not want to reopen an old debate, but I disagree. $_SERVER and prone to outside manipulation and not getenv().

> and they advised never to use getenv() over $_SERVER for precisely the issue I ran into today: some hosts don't pass all of the $_SERVER variables into the environment. 

That's a bullshit reason IMHO. They clearly do not want you top read ENV params since it may leak some of their infos and tell you to use a value that ANYBODY can change...

> The developers in the chat seemed to think it was worth considering ditching getenv() for $_SERVER in all cases and asked me to write this issue report.

Yeah cause they are lazy.

---

That being said, we could provide a way to switch to superglobals, at your own risk.

**Comment by nitriques** [comment]
For future readers, here the complete response from the host

> "Passing server variables through the environment was cool in 1999 when CGI was a thing, and web servers forked on every request and then forked again to run the CGI.
These days, PHP rarely runs inside the web server, it runs in its own dedicated process, so any presence of variables in the environment is a compatibility shim for scripts time-traveling from 1999 that should not be relied upon by current code."
"Of the two easiest (and therefore most common) ways of using PHP, one (Apache+mod_php) still only works with the one-process=one-request model so it populates the environment just like CGI used to do, and the other (FastCGI) employs a compatibility shim like I described above. (Basically it has a custom getenv that silently diverts to the list of server variables.)
No doubt the combo of those two does account for "most hosts" so that's probably why they didn't notice it.
One wonders whether the PHP folks ought to kick an E_DEPRECATED warning when getenv() is used that way for that reason.

**Comment by nitriques** [comment]
And it's the same batlle as HTTP_HOST vs. SERVER_NAME: should I trust value X or Y ...

**Comment by neosatus** [comment]
Here is the full conversation including my posts, I've also directed the guy from the host to this page so he can join the discussion:

> Me:
> Howdy all. I'm trying to learn Symphony and have been setting it up on a fresh site here on NFS. Apparently Symphony tries to call getenv('HTTP_HOST'), among many other variables, and they aren't part of the Environment according to phpinfo(), they only show up under $_SERVER which is bad practice I'm told. Is there a way I can get HTTP_HOST, and any other missing variables, into the Environment or is that something that is global to NFS?

>Him:
>$_SERVER is the correct place to find these values. 

>Assuming they are present in the environment is depending on a specific implementation detail, which is not advisable. 

>See the PHP documentation of the $_SERVER variable. It is the "official" PHP place to find values provided by the web server.

>Me:
>I got it working with the help of the kind people at Symphony by simply hard coding a setenv call at the top of index.php. 

>Regardless, they feel $_SERVER has issues with it and prefer setenv so if you y'all want people to be able to easily (albeit my fix was easy, figuring it out took some debugging) setup Symphony on this host, all you'd need to do is add HTTP_HOST to the Environment. NearlyFreeSpeech was on their compatible hosts list this morning but they removed it after helping me deal with the issues. If you'd like NFS put back on that list, I'd fix it and let them know.

>Him:
>Their feelings are wrong and not supported by the PHP developers. 

>But if they feel there is a problem with $_SERVER, they can file a bug report at bugs.php.net, preferably with a patch demonstrating their proposed fix.

>Me:
>Yea, they are having a discussion in the chat now about switching back to $_SERVER for all calls, so it sounds like you're in the right here.

>Him: 
>As soon as it is pointed out that the environment is not thread-safe, that discussion should be over. 

>Passing server variables through the environment was cool in 1999 when CGI was a thing, and web servers forked on every request and then forked again to run the CGI. 

>These days, PHP rarely runs inside the web server, it runs in its own dedicated process, so any presence of variables in the environment is a compatibility shim for scripts time-traveling from 1999 that should not be relied upon by current code.

>Me:
>It's pretty funny, apparently most hosts supply HTTP_HOST to the environment so this issue has never come up.

>Thanks for your help.

>Him:
>Of the two easiest (and therefore most common) ways of using PHP, one (Apache+mod_php) still only works with the one-process=one-request model so it populates the environment just like CGI used to do, and the other (FastCGI) employs a compatibility shim like I described above. (Basically it has a custom getenv that silently diverts to the list of server variables.) 

>No doubt the combo of those two does account for "most hosts" so that's probably why they didn't notice it. 

>One wonders whether the PHP folks ought to kick an E_DEPRECATED warning when getenv() is used that way for that reason.

>I stand corrected, mod_php uses a compatibility shim as well.

**Comment by nitriques** [comment]
Thanks!

**Comment by jdwx** [comment]
(Lead developer for PHP at the referenced provider here.)

> That's a bullshit reason IMHO. They clearly do not want you top read ENV params since it may leak some of their infos and tell you to use a value that ANYBODY can change...

Thank you for that thoughtful and completely incorrect characterization of our position.  You are of course welcome to review the full environment provided by our system for leaks of our infos:  https://php56.nfshost.com/  (Scroll down to the "Environment" section.)

Passing server variables via the environment was the done thing with CGI because it was pretty much that or pass them as command line arguments, which would have been *much* worse.  That is not how PHP is executed anymore, and it hasn't been for many years.  Server variables passed to PHP are effectively **never** actually passed through the environment.

In almost every commonly used SAPI that provides server values via getenv() / $_ENV, including both mod_php and FastCGI, "getenv" calls are implemented internally as compatibility shims that lookup the value in the same data used for $_SERVER.  The only SAPI I know of where this is *not* the case is the actual CGI SAPI in actual CGI mode, which executes now just as CGI did 15 years ago, and I certainly hope no one is still using that in 2016.  Thus, any "outside manipulation" that affects one will affect the other.

Given the above, if you believe that using getenv() provides protection against some sort of "outside manipulation" and you can substantiate that, a bug report to the PHP.net folks would probably be in order.

On the other hand, the original post said his problem was solved by (trivially) forging the environment variable he needed, so it's not clear what sort of protection against manipulation you feel using the environment is supposed to offer.

Perhaps you are confusing $_SERVER with $_REQUEST.  The latter populates from several different sources and does indeed have a track record of tricky requests passing GET parameters that overwrite values the expected to receive from other sources, with surprising and unexpected (and frequently insecure) results.

**Comment by nitriques** [comment]
Thanks for the answers. 

> Perhaps you are confusing $_SERVER with $_REQUEST. 

Yeah, not. See [this](https://www.drupal.org/node/2221699) about how one can manipulation $_SERVER

> so it's not clear what sort of protection against manipulation you feel using the environment is supposed to offer.

Remote manipulation.

> "getenv" calls are implemented internally as compatibility shims that lookup the value in the same data used for $_SERVER.

I'd like to see the code for that. I do not mind to be wrong (it's really the opposite). I want something secure and reliable, and from what I've seen, `getenv()` saves problems.

Also, why did you deactivate those shims ? and how ? (I am curious I want to know!)

> Thank you for that thoughtful and completely incorrect characterization of our position. 

I was not speaking directly about you (since at the time, I never actually interacted with you), mostly about my experiences with hosting providers. Did not wanted to start a war or anything.

**Comment by nitriques** [comment]
And sadly, [all anwsers](http://stackoverflow.com/questions/8798294/getenv-vs-env-in-php) tends to vote for `getenv()` .. I can't find any reason to not use it...

**Comment by jdwx** [comment]
Also, for your reference, there should not be a "battle" over the use of HTTP_HOST or SERVER_NAME, as the serve very different purposes.

HTTP_HOST contains the value of the HTTP Host: header provided by the client.  SERVER_NAME contains the (hopefully canonical) name configured by the server.

The former is primarily useful if one site is handling multiple names, to differentiate which one is being accessed.

It's certainly the case that since it is client-provided, the use of HTTP_HOST should largely be limited to comparing it to a list of hostnames it's OK to use (either by direct lookup or rigorous pattern matching), and a script that doesn't find a match should immediately die.  (Many security problems have been created by developers trying to hard to accept invalid data.)

**Comment by siimsoni** [comment]
@nitriques The Stack Overflow question is not really related to this topic. The difference between `getenv()` and `$_SERVER[]` is only that the first reads environment variables, and the latter reads an aggregation of values set by the web server. For HTTP_HOST **both get their values from the same source**.

There are some arguments related to portability of `getenv()`, but it's really an argument for using environment variables over values set by the web server in case you don't have a web server. It's not really possible to run Symphony CMS without a web server from command line; it would be nice if it was possible but that would require another interface.

**Comment by siimsoni** [comment]
@nitriques The [issue](https://www.drupal.org/node/2221699) you shared is great though, and it seems the agreed upon solution was to have application white-list any safe servers. Perhaps this could be considered for Symphony CMS as well?

**Comment by jdwx** [comment]
You have misunderstood the Drupal bug you reference.  It doesn't have anything to do with the $_SERVER variable, it has to do with the fact that the contents of HTTP_HOST (regardless of how they were obtained) are determined by the (potentially hostile) client.

The problem in that bug was that the input was not properly sanitized, not how the input was obtained.  getenv( "HTTP_HOST" ) would have returned the exact same value.

Similarly, the stack exchange post you refer to is about whether to use getenv() or $_ENV, not getenv() or $_SERVER.  And there is blatantly wrong info there.  E.g. "getenv() is yet another way to access data that PHP does not enable you to access directly" is completely wrong.  

When you call getenv() in PHP, you are not calling the C library getenv() function.  If you look at the PHP source for getenv() you will see it calls out to a SAPI-specific implementation, and that each SAPI-specific implementation does what it wants to fake up the the values.

It sounds like you might benefit from spending some time reading the PHP source code.

**Comment by jdwx** [comment]
"I'd like to see the code for that. "

The PHP source is available on github.

Look at: https://github.com/php/php-src/blob/PHP-5.6/sapi/apache2handler/sapi_apache2.c

Lines 252-265 show the implementation of getenv().

Lines 267-287 show how $_SERVER is populated.

Note they are both pulling from ctx->r->subprocess_env, which is apache's per-request internal table for passing server values to a subrequest.

Then look here:
https://github.com/php/php-src/blob/PHP-5.6/main/main.c

Line 2147 shows the sapi-specific getenv function being installed as the implementation of the PHP getenv() function.

Note that *nowhere* in this is the real C getenv() being called.

That's just one example (the most common).  Another common one is FastCGI:

https://github.com/php/php-src/blob/PHP-5.6/sapi/cgi/cgi_main.c

Lines 548-561 show the FastCGI implementation of getenv, which shows it looking up server values directly out of $_SERVER.  (Which is known as SG(server_context) in C.)

The FastCGI implementation does fall back to C getenv() if the value is not found in $_SERVER, creating one of those "magic" $_REQUEST-style values, with the potential problems that result.

**Comment by nitriques** [comment]
Wow thanks for all those answers :heart: 

>  It's not really possible to run Symphony CMS without a web server from command line

Many of us do by running custom php scripts from the command line.

> "I'd like to see the code for that. "

Yeah I should have said: I do know if I had the time to look it up. But hey, thanks!

> It sounds like you might benefit from spending some time reading the PHP source code.

You are right. But again, this takes time. Thanks for sharing yours ;) I now have multiple *other* questions I need to find answers to haha

> here should not be a "battle" over the use of HTTP_HOST or SERVER_NAME, 

There was ;)

> application white-list any safe servers. Perhaps this could be considered for Symphony CMS as well?

Yeah the goal was to avoid this...

@michael-e @brendo and thoughts on this ? 

Thanks a lot @jdwx and @siimsoni

**Comment by nitriques** [comment]
@jdwx  how did you deactivate the getenv call ?

**Comment by jdavidlists** [comment]
We didn't, it works fine.  Those variables are just not present in the environment on our system.

**Comment by neosatus** [comment]
See https://php56.nfshost.com/ for the phpinfo, same as the one I was using while debugging this issue earlier.

**Comment by jdwx** [comment]
We didn't disable it, it works fine (as shown in phpinfo).  But ours uses the real getenv() call.  As shown above, those variables aren't ever really present in the real environment anymore and our SAPI is one of the ones that does not use fakery to pretend they are.

**Comment by nitriques** [comment]
> We didn't disable it, it works fine

I meant why won't it return any value

> our SAPI is one of the ones that does not use fakery to pretend they are.

Oh that's how!

So what would you recommend ? Creating a custom shim to check first $_SERVER and fallback to getenv ?

Also, would happen to a server configured with the S in the variables_order ? getenv (if properly faked) would work ?

And do not get me wrong. I am not in love with getenv. I just remember that is solves bugs and I do not want to deal with them again ;)

**Comment by siimsoni** [comment]
> Many of us do by running custom php scripts from the command line.

I stand corrected. :)

> Yeah the goal was to avoid this...

There seem to be two essential paths here. Either secure the application with trusted hosts, or don't involve the application and assume what you get from the web server is secure.

**Comment by michael-e** [comment]
@nitriques: Let me sleep on it. I'll be back.

**Comment by jdwx** [comment]
If you're looking for SERVER_NAME, and it is not found in $_SERVER, that server is probably broken.  (HTTP_HOST depends on the presence of a Host: header from the client, so it could conceivably be missing, though if so that client would not be HTTP compliant and is probably a spambot.)

If you create a $_SERVER-then-getenv() shim, I hope you will put some thought into what valid circumstance you are trying to support in which $_SERVER is not populated, lest you create another exploitable "silent magic" behavior like $_REQUEST.

If you are determined to go that way, perhaps it's something you should test at install time and then pick the one that works and act that way consistently from there on.  That way, if the behavior changes later, due to malicious activity, broken config, etc., it will be noticed rather than silently obscured.

The variables_order setting won't affect getenv().  

Setting variables_order to exclude S would (in my opinion) be about the same as setting include_path to /var/empty.  It's possible, but it's not a configuration I would lose sleep trying to support. :)

**Comment by nitriques** [comment]
Ok thanks a lot @jdwx this has been a real eye opener. I (too often) want to 'fix' things fast to make the phone stop ringing (even tho I know it's not a good practice).

**Comment by nitriques** [comment]
@michael-e Thanks. BTW, the switch from $_SERVER to getenv was made a long time ago, in 2009: https://github.com/symphonycms/symphony-2/commit/7a8cee72cf7bf1a84b7c88c4cba518c75b61705e

**Comment by jdwx** [comment]
Believe me, I get that.  Those urges are very common.

It may help to keep in mind that often the primary beneficiaries of those urges are attackers.

Given that $_SERVER is the PHP official place that stuff is meant to be obtained, it seems reasonable to have "working PHP" as a system requirement for your app.  But then, I don't answer your phone.

If you do change to $_SERVER and you start getting a bunch of complaints that it's not working, I'd be very interested to know what environments those people are using.  Then again, one can never rule out the possibility of 1-click VPS web servers automisconfigured by people who have no idea what they're doing.  Happily that is not my circumstance. :)

**Comment by jdwx** [comment]
Alternatively, if you change it, and someone complains, and you tell them their host is wrong and their host shows up and says you're doing it wrong, just tag me in and I'll beat them up for you. :-)

The source is my ally, and a powerful ally it is.

**Comment by nitriques** [comment]
Thanks @jdwx :+1:

**Comment by neosatus** [comment]
Thanks for the above and beyond tech support, @jdwx.

**Comment by nitriques** [comment]
> just tag me in and I'll beat them up for you. 

Even if it's on Windows ? hahaha! The more I think about it, the more it looks like it was an Windows issue...

> Thanks for the above and beyond tech support, @jdwx.

Indeed. I wish I'd met tech support as good as this. (BTW I've added your company back on the compatible hosts since we will fix the issue)

**Comment by neosatus** [comment]
>The more I think about it, the more it looks like it was an Windows issue...

From one of the links you posted earlier, it said one of the main reasons for using setenv was because Windows uses 'Path' instead of 'PATH' and setenv would handle that difference while $_SERVER['PATH'] would cause a miss.

This issue was seen on FreeBSD 10.2, however.

**Comment by jdwx** [comment]
Really?  At some point getenv() didn't even work with IIS.  But that may even have been a few years before your 2009 switch.

But I'm pretty sure Windows/IIS uses FastCGI these days, so it should be a non-issue.

**Comment by jdwx** [comment]
PATH really is an environment variable and should correctly be pulled with getenv() / $_ENV.

**Comment by nitriques** [comment]
Wow :spaghetti: 

I'll be then carefull when I grep /getenv(/

**Comment by jdwx** [comment]
The list of things you should prefer to get from the environment is pretty short:
- USER
- LOGNAME
- TMPDIR
- SHELL
- HOME
- PATH

In most cases you still shouldn't come across these much.  PHP is typically going to intermediate between you and the environment.  E.g. TMPDIR sounds important but you should probably use tempnam()/ tmpfile().  PATH seems important but most (if not all, I just don't want to commit without checking) methods of external program execution already honor it where appropriate.

This definitely represents a shift, because in the days you are talking about (circa 2009), counting on PHP to do the right thing internally was really not a good idea. :-)  But now things have settled down and they have walked back a lot of the 3.x / 4.x era junk, so doing things PHP's way is how you avoid those annoying compatibility issues.  (The very same ones doing it the PHP way used to cause!)

**Comment by nitriques** [comment]
Heheheh thanks!

**Comment by brendo** [comment]
Looks like I'm late to the party, but I don't see any reason to prefer `getenv` over `$_SERVER` for [these four definitions](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/boot/defines.php#L207-L229).

If you need convincing, Symfony's Http component usually builds constructs a `Request` using the `$_SERVER` variables. 

Getting things from the environment is usually more useful when running things from the CLI, such as CI environments :+1:

**Comment by michael-e** [comment]
I am pretty sure that the switch from `$_SERVER` to `getenv` (@nitriques: thanks for finding this) had good reasons – but that was back in 2009.

So, after reading all of the above once again: We should use the `$_SERVER` superglobal. :+1:

In addition to the discussed `defines.php`, there is [one other ocurrence of `getenv`](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.page.php#L337) in the codebase.

**Comment by michael-e** [comment]
@jdwx: Thanks for taking the time for this discussion!

**Comment by nitriques** [comment]
> Getting things from the environment is usually more useful

That's what I am afraid of... so fall backing makes sense, but in the same time it could open security holes.

And reopen the battle over HTTP_HOST vs. SERVER_NAME :P

**Comment by michael-e** [comment]
> And reopen the battle over HTTP_HOST vs. SERVER_NAME :P

That would be a shame. Using `HTTP_HOST` makes a Symphony installation work on multiple domains!

I suggest to replace `getenv` with `$_SERVER`, erverywhere in the core, and without any fallback. There is no proof that any modern server might need a fallback.

**Comment by jdwx** [comment]
You could certainly create an abstraction, so that the decision of how to retrieve a particular value is made from exactly one place in the code.

**Comment by nitriques** [comment]
> Using HTTP_HOST makes a Symphony installation work on multiple domains!

Yeah but opens a security hole if the server is misconfigured... Thanks everybody for your input!
