### ISSUE TITLE
Symphony wants to manipulate tables that do not exist

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2663]
In `2.7.x` @michael-e has introduced »table locking« to prevent data corruption. This apparently leads to problems with fields that do not create an entry table since they do not store any data. 

I’ve encountered an error with the [system_date_fields](https://github.com/symphonists/system_date_fields/issues/20)-extension. See link for the corresponding issue.

To quote Michael:

> In your setup MySQL vomits on the fact that Symphony wants to manipulate tables which do not exist. Symphony has always assumed that these tables exist.

What would be the preferable solution? 

1. symphony checking if the table actually exists, or 
2. `system_date_fields` creating an empty table?

**Comment by michael-e** [comment]
@animaux and me verified (in the Gitter chatroom) that the issue is not caused by the table locking. If you remove the locking, you simply get the next error (related to Symphony's attempt to delete data from a non-existing table).

Here's the code in question: https://github.com/symphonycms/symphony-2/blob/2.7.x/symphony/lib/toolkit/class.entrymanager.php#L174-L221

You can see that Symphony tries to lock, delete a row and insert a new row in **each field's `tbl_entries_data_` table**. If this table doesn't exist, well, things can break (and I wonder why we have never noticed this before—could it be that thousands of such errors are buried in log files?)

**Comment by nitriques** [comment]
> What would be the preferable solution?

The solution is clearly 1). 

> could it be that thousands of such errors are buried in log files

Let me check that.

**Comment by nitriques** [comment]
We do:

> could it be that thousands of such errors are buried in log files

04/26/2017 5:15 pm > UNKNOWN: DatabaseException 0 - MySQL Error (1146): Table 'sym_copy.sym_entries_data_14' doesn't exist in query: LOCK TABLES sym_entries_data_14 WRITE on line 961 of S:\github\symphony-2 - Copie\symphony\lib\toolkit\class.mysql.php

**Comment by nitriques** [comment]
I've tested PHP 5.6.30, 7.0.18 and 7.1.4. They all work and they all vomit in the logs.

**Comment by animaux** [comment]
Thanks @nitriques. So much sorrow in all those logfiles. \*sigh\*

**Comment by nitriques** [comment]
Turns out it's @michael-e's fault haha. Sending a PR with a fix right now
