### ISSUE TITLE
[2.7.0RC1] Undefined variable

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2719]
My debugger throws up because of [this new delegate][1]. It says `$c`is undefined, and I’m not exactly sure what `$c`should be or where it comes from.

[1]: https://github.com/symphonycms/symphony-2/blob/2.7.x/symphony/lib/toolkit/class.administrationpage.php#L1072

**Comment by nitriques** [comment]
It's a copy paste from elsewhere. I knew I had some unfinished business in 85f30f3e4caaf2983c770e08b28011e9bdc82319 but could not figure out what it was since it has been coded more than a year an a half ago... But I had confidence in it since it ran in production since the same period of time... Thanks to your debugger than!
