### ISSUE TITLE
Make the auth token LONGER

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2724]
This is a breaking change, as it would invalidate all current auth token url.

But this change is needed.

Current implementation uses 8 chars: I propose 40 (SHA 1 = 160 bits, not truncated, which means 40 characters in HEX)

I propose to use sha256 also.

Re #2711

**Comment by michael-e** [comment]
> I propose 40 (SHA 1 = 160 bits, not truncated, which means 40 characters in HEX)

Yep, that was my proposal as well.

> I propose to use sha256 also.

What do you mean with this? Use a longer hash? I'd think that 160 bits of entropy would suffice, so on the long run I'd rather go for something as random as possible.

**Comment by nitriques** [comment]
>  I'd rather go for something as random as possible.

That why I want to use sha256, since sha1 is broken. But I would clip it to 40 chars.

**Comment by michael-e** [comment]
I meant: Shouldn't we use an "auth token" that is not derived from user data? If we use random bytes (instead of the username), we could simply hex encode these. No need to use (resp. misuse) a hashing algorithm. In the shell you would do this like so:

```sh
dd if=/dev/urandom bs=20 count=1 2> /dev/null | od -A n -t x1 -v | tr -d " \n"
```

or with openssl:

```sh
openssl rand -hex 20
```

(Sorry, I don't know how to do it with PHP.)

Of course, since the random bytes are not derived from the username, we would have to save the result in the database.

**Comment by nitriques** [comment]
You are totally right!

> since the random bytes are not derived from the username, we would have to save the result (or a secure hash) in the database.

Yeah that's what I wanted to avoid.

I am hope to voting on that! But I think that username + already salted password is random enough, Information is lost. You can't derived it.

**Comment by nitriques** [comment]
It also has the advantage of making sure it gets invalidated when the password changes.

**Comment by michael-e** [comment]
Still I think that the "auth token" idea is more secure and more flexible, also because an auth token can be invalidated independently from the password. That's why so many web services use it. :-)

Let's see what others think.

**Comment by nitriques** [comment]
@michael-e When would you generate the token ? When/how would you generate it ?

**Comment by michael-e** [comment]
Like in many web services: Klick a button to generate a token. Klicking again generates a new token, so the old one doesn't work anymore.

Luxury version: Multiple independant tokens. We don't need this, I think.

**Comment by michael-e** [comment]
We could do s.th. like this:

```php
$token = bin2hex(openssl_random_pseudo_bytes(16));
```

AFAIK, this means 128 bit enthropy (ideally, if the random bytes are truely very totally super random), which should be enough. If you want to make it "insanely secure", you can use:

```php
$token = bin2hex(openssl_random_pseudo_bytes(20));
```

**Comment by nitriques** [comment]
Great. By default, should a user have a token ? Would we need to keep the "login from token" checkbox ? Or getting a token is sufficient ?

**Comment by nitriques** [comment]
> If you want to make it "insanely secure",

I like that.

**Comment by michael-e** [comment]
I think that the user should not have a token by default, and remote login should be disabled. But each time you click a button (respectively mark the checkbox "allow remote login"), a new token gets generated/saved, and the resulting login URL will be displayed. Since there should also be the possibility to disable login, a checkbox is not bad! When you deselect it, we can drop the token.

**Comment by nitriques** [comment]
Ok I think this is a pretty good plan. Thanks.
