### ISSUE TITLE
If the DB user can't lock the table, we get a "Entry saved" message

### ISSUE THREAD

**Issue by nitriques** [symphonycms/symphony-2#2752]
Affected Symphony version(s) : 2.7.0
PHP version(s) : ALL
OS(es) : ALL

@michael-e was that intended ? Thank god I was able to find it in the log.

Just stumbled upon this case where the DB user did not had the `LOCK TABLES` privilege. Should we deal with it ? (That same user did not had `ALTER` either and when I updated extension, I did received the MySQL error message).

**Comment by nitriques** [comment]
Side note: I currently use `SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,LOCK TABLES`. Should we add this to the readme ?

**Comment by michael-e** [comment]
No, that was not intended. Honestly, I never thought about it, because in every hosting environment I ever worked with the DB user had all permissions (except GRANT, of course).

Nevertheless, this behaviour is not optimal.

Symphony attempts the lock inside a try/catch statement — but it only writes to the log file if it fails. Maybe we should throw the exception to the frontend as well?

**Comment by nitriques** [comment]
> because in every hosting environment I ever worked with the DB user had all permissions 

Yup!

Honestly, I do not know how to handle it ;) Maybe @jensscherbl has an idea...

**Comment by michael-e** [comment]
> Should we add this to the readme ?

It might confuse users. WordPress, for example, also [doesn't talk about database privileges](https://wordpress.org/about/requirements/) at all. As mentioned, I wouldn't expect any problems on shared hosting. And if you are using your own servers, it will be simple to fix the issue once you notice it (see above, my suggestion to throw the exception).

**Comment by nitriques** [comment]
Ok good point.

I fear that throwing the exception might be dangerous as well: do we continue to save other fields ? I think that's is what is happening with an exception right now...

**Comment by michael-e** [comment]
Hmmm. Doesn't the complete PHP process in Apache terminate when the output has been "printed"? I thought so, but I may be wrong, of course.

**Comment by nitriques** [comment]
Exception throw normally yes: but the whole process is wrap in another try catch me thinks...

**Comment by michael-e** [comment]
Even if the script does not "intend to terminate", won't Apache kill the whole thread/process?

**Comment by michael-e** [comment]
Symphony's exception handler function ends with:

```php
echo $output;
exit;
```

`exit` is pretty clear. It doesn't depend on any "loop hierarchy" like `break`does. So I wouldn't expect anything to happen afterwards. @jensscherbl ?

**Comment by nitriques** [comment]
> Even if the script does not "intend to terminate", won't Apache kill the whole thread/process?

Not if it is catched by any method in the stack where it's thrown. Only if the Exception reach the end of the stack is the handler involved.

**Comment by nitriques** [comment]
Would trying to save without locks be ok ?

**Comment by michael-e** [comment]
Trying to save without locks is a workaround that I don't really like. This would mean that race conditions can occur, but the developer will not notice (unless he reads the logs, which is not very common IMHO). I would prefer a solution that breaks the page.

If I understand correctly, you fear that the exception is catched somewhere else, without reaching the exception handler? Can this happen? (I don't know, due to my lack of knowledge.)

**Comment by jensscherbl** [comment]
> Would trying to save without locks be ok ?

Would leave it as is and just require the user privilege for the database.

> `exit` is pretty clear. It doesn't depend on any "loop hierarchy" like `break` does. So I wouldn't expect anything to happen afterwards.

That’s right.

**Comment by nitriques** [comment]
Ok then, I'll try to find a fix. Thanks guys.

**Comment by creativedutchmen** [comment]
Interesting stuff, guys. I do wonder if much of this could be "fixed" more neatly when the entire save was done in a transaction? That way, when an error occurs (on the second write, say), there is no data loss.

Might be quite a rewrite, though, and since I won't be doing it, you might as well take my comment with a grain of salt ;)

**Comment by nitriques** [comment]
@creativedutchmen I have transactions ready for `3.0.0`. I still have lots of work to be done, but it is coming.
