### ISSUE TITLE
Log::pushToLog – calls should be fixed

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2768]
Affected Symphony version(s) : 2.7.x
PHP version(s) : all
OS(es) : all

There are some calls to `Log::pushToLog` in the Symphony core which don't honor the function's signature. (Parameters are missing.)

**Comment by nitriques** [comment]
Only the first one is required. The remaining 4 are all optional (since they have a default value in the function signature), so they are all ok !!

PHP does not let you call function will less then the minimum number of parameters. But it lets you call function on which you pass more arguments then needed.
