### ISSUE TITLE
Textareas do not always preserve content

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2819]
Affected Symphony version(s) : since 2.3
PHP version(s) : all
OS(es) : all

Symphony's textareas do not always preserve the content.

This has to do with the usage of `General::sanitize` when preparing the content for the browser. The sanitize function has been changed a long time ago in order to prevent double encoding: https://github.com/symphonycms/symphony-2/commit/444475fb76399a1e3d725e923cb3366cd6826e21

This may have solved certain problems with double-encoding (I haven't done any research on this), but it has created an issue for textareas. For example, save the following:

```html
<div>&gt; hello</div>
```

After saving, the textarea will display:

```html
<div>> hello</div>
```

How bad. You can not save this again without fixing it.

I think that textareas should **not** use `General::sanitize` at all in `displayPublishPanel`, because the task here is not simply sanitizing but *displaying the original content in the browser*. So my suggestion is to replace `General::sanitize($value)` with `htmlspecialchars($value, ENT_COMPAT, 'UTF-8', true)` in `fieldTextarea::displayPublishPanel`.

Any thoughts on this are welcome.

**Comment by cylkee** [comment]
I've used Symphony since 2.3 and I've have a similar issue with saving `&nbsp;`.

I think I would prefer to see the HTML entity on save, instead I see a blank space and it's not possible to discern non-breaking spaces from regular spaces until it's output.

If a textarea with invisible non-breaking spaces is copied to clipboard, certainly in Windows, pasting to another textarea converts the non-breaking spaces to regular spaces.  Showing HTML entities in textarea would prevent this.

**Comment by michael-e** [comment]
Good news: Your issue would be solved with the proposed fix. :-)
