### ISSUE TITLE
Leaving GitHub?

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2850]
At the moment a lot of people switch to GitLab, because GitHub has been acquired by Microsoft. We all know that this acquisition does not immediately mean any concrete threat, so leaving GitHub now is more a matter of attitude than anything else.

I personally vote for leaving. But it would definitely mean a lot of work, especially for @nitriques. (Moving the repos is simple, but I am sure that there would be **a lot** of side effects on the whole ecosystem!) So I would not want to push anybody. @nitriques is the chief developer, so IMHO it's his decision.

I just wanted to say: If Symphony moves to GitLab, I will follow.

**Comment by nilshoerrmann** [comment]
We are using Gitlab for another project. Github is better and I‘d recommend to continue using it.

Besides reservations against Microsoft, what’s the reason behind this idea besides self-hosting?

**Comment by michael-e** [comment]
Microsoft wouldn't acquire GitHub if it wasn't about *control* and *influence*. (And they wouldn't pay so much money either.) It will by a step-by-step process, of course. But IMHO it is not desirable, no matter how small single steps will be.

(BTW, I am not sure at all that self-hosting would be better for a project like Symphony.)

**Comment by nilshoerrmann** [comment]
I understand that feeling and it’s good to know alternatives and to be prepared. But right now the product hasn’t changed and it’s still the better product in my eyes.

That said, I’m not an active contributor anymore. But please don’t make rushed decisions.

**Comment by michael-e** [comment]
Thanks! I am not for rushed decisions either; that's why I tried to be careful with my initial post.

**Comment by NetLancer** [comment]
No wonder if gitlab's gradually getting attention of another GIANTSOFT ..

**Comment by animaux** [comment]
> Github is better and I‘d recommend to continue using it.

Elaborate! `:)`

**Comment by animaux** [comment]
> No wonder if gitlab's gradually getting attention of another GIANTSOFT ..

Any source for that info?

**Comment by twiro** [comment]
I'm strictly against this unless Microsoft shows **clear signs** they're going to spoil the party here (which I hope and believe they won't do).

Moving to Gitlab might me a manageable task for the Symphony main repo, but it won't be so for lots of more or less abandoned or seldom-used extension repos. Trying to move **all** symphony related repos to gitlab will therefore fail and we will end up with having the main repo and most current and actively developed extensions on gitlab while lots of older extensions will remain on github.

In my eyes Symphony currently hasn't the "powers" to make such a move in a way the eco-system could actually benefit from it. We had the powers to make the move from self-maintained to github back in the days and should still be thankful for what we achieved with that move and the [great additions to the symphony-eco-system](http://symphonyextensions.com) that were built on top of the new gained possibilities of a central git-based repo-platform.

And speaking about [symphonyextensions.com](http://symphonyextensions.com) we should be especially thankful that it's still there, running reliable and giving an **up-to-date** overview of a **solid majority** all extensions from the symphony-cosmos though its codebase nearly hasn't been touched since @nickdunn built it in the heydays of Symphony. Moving to gitlab will definitively break this too and my fear is that if that happens it won't get it fixed as we simply don't have the resources (just like getsymphony.com is more or less in kinda _"dead"_-mode since the blog and forum were ditched for gitter).

And while I don't really know which parts of github-based data and infrastructure we would loose while moving (I'm talking about prs, issues, discussions, stars, etc. from people that won't make the move) I'm pretty certain trying to move everything sympohny-related to github will spoil a lot on this level also.

But apart from my fear that such a move will harm the already fragile symphony-eco-system I simply don't share your sentiments against Microsoft  (though I'ma Mac user since 10 years):

> _Microsoft wouldn't acquire GitHub if it wasn't about control and influence._

> _»MS Github« will most definitely make use of all the newly available data in order to maximise their profits and market share in ways I can hardly imagine_

Do you really think? I'm not so sure… regarding all the work MS has put into [Visual Code Studio](https://code.visualstudio.com/) recently and all the praise they've earned from developers for it I think their motivation in buying github lies in **attracting developers** rather than scaring or exploiting them. I found [this article](https://www.linuxfoundation.org/blog/microsoft-buys-github-the-linux-foundations-reaction/) (linked by @nitriques on twitter?) pretty interesting and I would propose to at least give them an honest chance reagarding their vision for github.

If Microsoft proves me wrong and real threats arise we will still have the time to move on! Until then I'd suggest we spend the time we can afford for symphony [more productive](https://github.com/symphonists/symphony-extensions-network/issues/19) ;)

**Comment by twiro** [comment]
By the way: As I just adopted the [geocoding-extension](https://github.com/twiro/geocodingfield) yesterday and as @klaftertief was so kind to give @nitriques [access to all his other extension-repos](https://github.com/symphonists/symphony-extensions-network/issues) I have to say that **regaining access to abandoned extension-reops** by adopting them (if you use them yourself) or getting them moved to the [symphonists-account](https://github.com/symphonists) is something we should really enforce and do as much as we can!

Not only does it help to keep our extension-eco-system on github and symphonyextensions.com healthy but it would also **greatly improve our "starting position" in case we'd really decide to make the move to gitlab**.

I know just forking and fixing stuff for oneself is always easier, but **having a well-maintained and solid-documented main-repo is so much better** than a couple of different forks with different fixes.

**Comment by nilshoerrmann** [comment]
> Elaborate! :)

My main point: the UI and UX is confusing, cumbersome and buggy. It all looks quite similar at first sight and the general functionality is the same (a pull request becomes a merge request – things you get accustomed to quite quickly). But too often views don't load or you are completely lost because the navigation seems to be split and randomly distributed in all cardinal directions. 

Generally, things have a tendency to behave slowly due to the JavaScript based interface. A problem that Github faces as well well with there new activity stream layout though. But still, I'm often surprised how well Github works compared to Gitlab when coming back after a while.

**Comment by animaux** [comment]
Thanks for elaborating Niels. I have yet to make those experiences.

**Comment by michael-e** [comment]
I didn't intend to discuss which one is better. This is not the question.

And despite my personal opinion I just said "@nitriques should decide" and "if Symphony leaves, I will follow". I don't want to create any pressure, and I don't want to be engaged in an emotional discussion. (Why emotional? Because we can only discuss what we *believe* or *want* to be true. No hard facts.)

So I think that this issue should be closed as soon as @nitriques has chimed in and posted his decision on the matter.

**Comment by nitriques** [comment]
Yeah, it's cool to talk about it, I appreciate the feedback really ;)

I am typing this on a Windows computer, wearing a Microsoft jacket.
Github is a wonderful software and I am pretty sure nothing bad will happen to it. Many of their employees work with it and they will not want to piss their devs.
I've used Bitbucket and gitlab (both recently) and I prefer github. 
I feel like Microsoft is the best company to acquire it. VC wants their money back, si it was inevitable for a 10 years old start up. And I do trust Nat Friedman.

If you fear Microsoft, you must also fear Google, Amazon, Facebook, Twitter and many more ;)

**Comment by animaux** [comment]
> If you fear Microsoft, you must also fear Google, Amazon, Facebook, Twitter and many more ;)

I do! `;)`

Thanks for that clear statement.

**Comment by nitriques** [comment]
> Thanks for that clear statement.

No problem. And do no be confused: I know what does companies can do. I sometimes fear them. They can do real creepy and crapy things. They have immense power. We must accept the risk or live disconnected.

**Comment by michael-e** [comment]
> > If you fear Microsoft, you must also fear Google, Amazon, Facebook, Twitter and many more ;)
>
> I do! ;)

So do I.

> I am typing this on a Windows computer, wearing a Microsoft jacket.

I hope that I won't dream of this tonight. 

:-)

Thanks, @nitriques!

**Comment by animaux** [comment]
I think it’s most likely my utter unspeakable hate of Word® that makes me distrust MS.

**Comment by munki-boy** [comment]
![519285ffecad046054000014-750](https://user-images.githubusercontent.com/4517581/41284594-ae3a2644-6e31-11e8-87b1-ecd1537d1c82.jpg)

> It looks like you're trying to leave Github

**Comment by animaux** [comment]
https://twitter.com/_disco/status/1003684420526669826

**Comment by animaux** [comment]
@nilshoerrmann you could join Gitlab and improve it `;)` —> https://twitter.com/andreasmarc/status/1006243013801271296
